### ISSUE TITLE
errors getting started attaching role to user

### ISSUE THREAD

**Issue by isimmons** [Zizaco/entrust#103]
Following the readme
This part works  

```
$owner = new Role;
$owner->name = 'owner';
$owner->save();

$admin = new Role;
$admin->name = 'admin';
$admin->save();
```

Then when attaching the role to the user I tried both ways and get an error

```
$user = User::find(1); //works
$admin = Role::where('name', '=', 'admin'); //works

//Then fail
$user->attachRole($admin);
//Call to undefined method Illuminate\Database\Query\Builder::getKey()

//$user->roles()->attach($admin->id);
//Undefined property: LaravelBook\Ardent\Builder::$id
```

Using laravel 4.1.*
Tried dev-master and backing up to stable release of both Entrust and Ardent.

Am I supposed to do anything else with the models besides copy/paste from the readme and add the HasRole trait to my User model?

**Comment by vixxjy** [comment]
@mrsimonbennett thanks for your suggestion.
