### ISSUE TITLE
attachRole($role) doesn't check if role is already attached

### ISSUE THREAD

**Issue by mihai-craita** [Zizaco/entrust#106]
Hello I noticed that you can have have in the 'assigned_roles' table same user with same role many times.
Function attachRole doesn't check if role is already attached.
User with the same role multiple times has no meaning.

Thanks!

**Comment by shraddhabanerjee** [comment]
Was the issue resolved? If yes, how?

**Comment by mihai-craita** [comment]
I used the following code:

```
$user->roles()->sync($roles);
```

**Comment by shraddhabanerjee** [comment]
Thanks @mihai-craita.

But I am getting the error while using this.

ErrorException in BelongsToMany.php line 806: Argument 1 passed to Illuminate\Database\Eloquent\Relations\BelongsToMany::formatSyncList() must be of the type array, object given, called in /var/www/vurtax/Vurtax/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php on line 771 and defined

**Comment by mihai-craita** [comment]
As the error says you have to pass an array of roles ids something like this: `[1,2,3]`

**Comment by shraddhabanerjee** [comment]
Hey @mihai-craita Thanks a lot.. 
It worked ! Just sent one role in the array that I wanted to assign.

**Comment by mihai-craita** [comment]
@shraddhabanerjee Great! Take care! :)
