### ISSUE TITLE
Detach all Roles from a user

### ISSUE THREAD

**Issue by fatstar** [Zizaco/entrust#131]
Is any easy way to detach all roles from a user at once ?
Such as deatchRoles() or detachRoles(*).

**Comment by vyquanghoa** [comment]
$userModel = User::find(1);
$userModel->detachRoles($userModel->roles);

**Comment by azulkipli** [comment]
Regarding "detachRoles()" I think should be written on README.md :)

**Comment by MartinJHammer** [comment]
@viquanghoa Worked like a charm :) When do I learn to simple check out the traits I'm using?

**Comment by amir751020** [comment]
Just a hint, never ever use something like this
`$user->roles()->delete()`
This is a catastrophe in your Database!
It will remove this users roles from all users (role_user table)
It will remove this users roles from the roles table (Which is wrong! we are trying to just delete the currentUser role from the role_user)

**Comment by mhelaiwa** [comment]
This will remove all user roles and trigger cache reset of laratrust .. And all is done with one query so there is no need to get all user's roles for delete

```$userModel->syncRoles([]);```
```$userModel->detachRoles();```
