### ISSUE TITLE
Ability to add permissions to users.

### ISSUE THREAD

**Issue by phazei** [Zizaco/entrust#155]
Sometimes some users need much more granular authorization that what roles can provide.  Currently, if a user needs anything a role doesn't provide, it would require creating a unique role just for them.  If permissions could be assigned to a user, then they could be given a role, in addition to a permission or two that they might also need.  I think it would be a relatively simple addition that would provide much greater functionality.

**Comment by uzegonemad** [comment]
Sorry to revive an old issue but I just wanted to point out that I've written a guide to bringing user-based permission support to Entrust.

This is *probably* forward compatible if Entrust's API doesn't change drastically. Use it at your own risk / mental state.

https://gist.github.com/uzegonemad/38608e137f7e8f95d933
