### ISSUE TITLE
change autoincrement to uuid

### ISSUE THREAD

**Issue by ttanai** [Zizaco/entrust#186]
impossible to change autoincrement field to uuid, because Entrust refer directly to tables:
DB::table(Config::get('entrust::assigned_roles_table'))

in this way, cannot change autoincrement field to uuid field (necessary in clustered environment).

Better solution, if you refer to Model, there can be overwrite id field

class Role extends EntrustRole
{
    public static function boot()
    {
        parent::boot();
         static::creating(function ($model) {
            $model->id = (string)$model->generateNewId();
        });
    }
    public function generateNewId()
    {
        return Uuid::uuid4();
    }

**Comment by Zizaco** [comment]
I'm afraid you will have to extend the main classes and to inject the extended one into IoC container

**Comment by webkenny** [comment]
Would you mind elaborating a little on your comment? I do want to use this package to handle roles in an application I am building but we have a business case to use UUIDs for the users and not IDs. Which classes would we need to extend here and what would be the preferred method to inject so as not to disrupt the main functionality?
