### ISSUE TITLE
Can't Install on laravel 5

### ISSUE THREAD

**Issue by dearteno** [Zizaco/entrust#196]
in console he said 
Problem 1
    - Installation request for zizaco/entrust dev-master -> satisfiable by zizaco/entrust[dev-master].
    - Conclusion: remove laravel/framework 5.0.x-dev
    - zizaco/entrust dev-master requires laravelbook/ardent ~2.4 -> satisfiable by laravelbook/ardent[v2.4.0, v2.4.1, v2.4.2].
    - laravelbook/ardent v2.4.0 requires illuminate/validation ~4.1 -> satisfiable by laravel/framework[4.1.x-dev, 4.2.x-dev], illuminate/validation[4.1.x-dev,

**Comment by BrunoQuaresma** [comment]
@bart  Im still with the same problem. I update my composer.json and require credentials to API.

**Comment by bart** [comment]
@BrunoQuaresma Did you try the above entries in composer.json?

**Comment by BrunoQuaresma** [comment]
@bart sorry... i can install :+1: 

```
"laravelbook/ardent": "dev-l5 as 2.4.2",
"zizaco/entrust": "1.3.*@dev",
```

**Comment by bart** [comment]
Hm I think they updated some stuff in the current develop branch of laravel / framework. I will have al ook at it asap!

**Comment by BrunoQuaresma** [comment]
Nothing change for the "package" method... :/

**Comment by Vasiharan** [comment]
I also get 'BadMethodCallException' error

```
exception 'BadMethodCallException' with message 'Call to undefined method [package]' in /vagrant/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php:140
Stack trace:
#0 /vagrant/vendor/zizaco/entrust/src/Entrust/EntrustServiceProvider.php(21): Illuminate\Support\ServiceProvider->__call('package', Array)
#1 /vagrant/vendor/zizaco/entrust/src/Entrust/EntrustServiceProvider.php(21): App\Providers\RoleServiceProvider->package('zizaco/entrust', 'entrust', '/vagrant/vendor...')
#2 /vagrant/app/Providers/RoleServiceProvider.php(22): Zizaco\Entrust\EntrustServiceProvider->boot()
#3 [internal function]: App\Providers\RoleServiceProvider->boot()
#4 /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php(523): call_user_func_array(Array, Array)
#5 /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(597): Illuminate\Container\Container->call(Array)
#6 /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(579): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\RoleServiceProvider))
#7 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\RoleServiceProvider), 19)
#8 /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(580): array_walk(Array, Object(Closure))
#9 /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(15): Illuminate\Foundation\Application->boot()
#10 /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(151): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#11 /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(180): Illuminate\Foundation\Application->bootstrapWith(Array)
#12 /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(89): Illuminate\Foundation\Console\Kernel->bootstrap()
#13 /vagrant/artisan(34): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 {main}

Script php artisan clear-compiled handling the post-update-cmd event returned with an error
                      
```

Any ideas?

**Comment by BrunoQuaresma** [comment]
Just comment the line that call the package method in Entrust's Service Provider. In Laravel 5 the package method is removed.

**Comment by Vasiharan** [comment]
Thanks, yes that seems to work! This probably means all Laravel packages will need updating... looks like a non backward compatible change for Laravel 5... :(

**Comment by dylanharbour** [comment]
Ok, for those that are still a little confused, here's how I got it to install with Composer (all details are above, but this is just the easier to follow version!)

* Add  the following to the  "require" section of your composer.json    
```
    "laravelbook/ardent": "l5-dev as 2.4.2",
```
* Add the following repository to your composer.json (I put mine below "type", above "require")

```
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/bart/ardent.git"
        }
    ],
```
* Do a composer update. You'll get the "Bad method call exception". Comment out the following line in the 'EntrustServiceProvider.php' file 
```
    $this->package('zizaco/entrust', 'entrust', __DIR__.'/../');
```
I'm still playing with entrust, so I cannot confirm if everything is working correctly yet. But it did at least install!

**Comment by bart** [comment]
After I've merged my project to 5.0 stable I've updated the fork as well, so you don't need to remove the package() method call manually anymore.

**Comment by bart** [comment]
Published changes for Laravel 5.0. Please pull in https://github.com/bart/entrust.git as repository as well and reference it in your composer.json like this:

"zizaco/entrust": "l5-dev as 1.3.0",

**Comment by simonfranz** [comment]
is there any news on using ardent and entrust with laravel 5? i don't get this working in a new project.

**Comment by bart** [comment]
What is not working? How does your composer.json file look like?

**Comment by simonfranz** [comment]
uff, seems there was a mistake by me 

with this it's working, thank you very much

        "require": {
            "laravel/framework": "5.0.*",
            "laravelbook/ardent": "dev-l5 as 2.4.2",
            "zizaco/entrust": "1.3.*@dev"
        },
        "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/bart/ardent.git"
        }
    ],

**Comment by dylanharbour** [comment]
I'm still not winning with this on L5. After following the installation process (with repositories listed above) and by commenting out the the offending lines in the 2 service providers, I manage to get everything to install fine. 

The problem seems to be when it comes to using it, If you try attach any of the relationships, things fail (on the belongsToMany part of the eloquent model)

Try attachRole or attachPermission and the error received is  
```
'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class name must be a valid object or a string' in /Users/.../vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:980

```
I'm leaning towards this being caused by the new namespacing changes in L5, but could be wrong.

Has anyone been able to get the versions described in SimonFranz's composer.json to work on the stable branch of L5?

**Comment by bart** [comment]
Yes, I did. Did you publish the config by using the vendor:publish console command?

**Comment by dylanharbour** [comment]
Thanks Bart! 

I wasn't including your entrust repo, which was causing all of the chaos. 

Would you consider your repo safe to use on production?

**Comment by bart** [comment]
Yes, it is safe to use on production, because we are using it in out company, too. But if you really want to use a L5 package, I can suggest https://github.com/caffeinated/shinobi. That's what I'm currently trying out, too.

**Comment by dylanharbour** [comment]
Thanks for all the hard work. This has saved me a lot of frustration! Caffeinated looks interesting, although the documentation is a little thin, I like that it's built for L5. 

I'll definitely check it out, but I'll stick to entrust for this project.

**Comment by andrewelkins** [comment]
For Laravel 5, Try the new [laravel-5](https://github.com/Zizaco/entrust/tree/laravel-5) branch.

**Comment by canfiax** [comment]
thanks @bart. I submitted a pull request for your fork.

**Comment by bart** [comment]
Perfect, thanks!
