### ISSUE TITLE
Entrust with Laravel 5 - MigrationCommand not found

### ISSUE THREAD

**Issue by WayneHarris** [Zizaco/entrust#204]
Have Entrust on a Laravel 5 project using the following composer method to install.
#196 

But now have a error with Migration Command not found when running artisan after 

'Zizaco\Entrust\MigrationCommand' not found in vendor/zizaco/entrust/src/Entrust/EntrustServiceProvider.php on line 58

Any ideas?

**Comment by LMCom** [comment]
I cannot thank you enough. Without your fix, composer was unable to update Laravel to version 5, because of https://github.com/Zizaco/entrust/issues/196.
