### ISSUE TITLE
Laravel 5: Class 'App\Permission' not found

### ISSUE THREAD

**Issue by JoolsMcFly** [Zizaco/entrust#214]
Hey guys,

I am having issues using Entrust with Laravel 5.

For the sake of simplicity here's the simplest code snippet to repro my issue..
```php
//HomeController.php
    if ( \Auth::user()->can(VIEW_ACCOUNTS_PERMISSION)) {
      die("OK");
    }
    else {
      die("KO");
    }
```

Running above code I get:
Class 'App\Permission' not found

I traced things down with xdebug and error happens in Entrust/HasRole.php:
```php
            // Validate against the Permission table
            foreach ($role->perms as $perm) { // here!
                if ($perm->name == $permission) {
                    return true;
                }
            }
```

which calls
```php
    /**
     * Many-to-Many relations with Permission named perms as permissions is already taken.
     *
     * @return void
     */
    public function perms()
    {
        // To maintain backwards compatibility we'll catch the exception if the Permission table doesn't exist.
        // TODO remove in a future version.
        try {
		return $this->belongsToMany($this->getAppNamespace().Config::get('entrust::permission'), Config::get('entrust::permission_role_table'));
        } catch (Exception $e) {
            // do nothing
        }
    }
```

The issue seems to be with AppNamespaceDetectorTrait::getAppNamespace which returns App\ so belongsToMany tries to load App\Permission.php instead of App\models\Permission.php

Here's my composer PSR4 definition:
```json
//composer.json
		"psr-4": {
			"App\\": "app/",
			"MyCompany\\": "app/MyCompany"
		}
```

Any idea?

**Comment by andrewelkins** [comment]
Please test with the [laravel-5](https://github.com/Zizaco/entrust/tree/laravel-5) branch

**Comment by JoolsMcFly** [comment]
Hey guys,

sorry I didn't get back to you earlier.
Adding namespaces didn't fix it but now L5 is out everything works as expected.

Thanks.

**Comment by vivex** [comment]
I am also facing the same issue with laravel 5, creating Role & Permission giving no error but assign permission to role giving following error
 $guestRole->attachPermission($browseZurtrPermission);
 i am running this code in seeder class and have my  Entity defined in \App\Entity namesapce and each file (role,permission entity & seeder) have proper namespace declaration & use. Following is the stack trace of error -


 php artisan db:seed


Do you really wish to run this command? [y/N] y
PHP Fatal error:  Class '\Permission' not found in /var/www/html/sac/storage/framework/compiled.php on line 9534
PHP Stack trace:
PHP   1. {main}() /var/www/html/sac/artisan:0
PHP   2. Illuminate\Foundation\Console\Kernel->handle() /var/www/html/sac/artisan:36
PHP   3. Symfony\Component\Console\Application->run() /var/www/html/sac/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:90
PHP   4. Symfony\Component\Console\Application->doRun() /var/www/html/sac/vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   5. Symfony\Component\Console\Application->doRunCommand() /var/www/html/sac/vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP   6. Illuminate\Console\Command->run() /var/www/html/sac/vendor/symfony/console/Symfony/Component/Console/Application.php:874
PHP   7. Symfony\Component\Console\Command\Command->run() /var/www/html/sac/vendor/laravel/framework/src/Illuminate/Console/Command.php:101
PHP   8. Illuminate\Console\Command->execute() /var/www/html/sac/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
PHP   9. Illuminate\Container\Container->call() /var/www/html/sac/vendor/laravel/framework/src/Illuminate/Console/Command.php:115
PHP  10. call_user_func_array() /var/www/html/sac/storage/framework/compiled.php:925
PHP  11. Illuminate\Database\Console\SeedCommand->fire() /var/www/html/sac/storage/framework/compiled.php:925
PHP  12. DatabaseSeeder->run() /var/www/html/sac/vendor/laravel/framework/src/Illuminate/Database/Console/SeedCommand.php:57
PHP  13. Illuminate\Database\Seeder->call() /var/www/html/sac/database/seeds/DatabaseSeeder.php:19
PHP  14. RoleSeeder->run() /var/www/html/sac/vendor/laravel/framework/src/Illuminate/Database/Seeder.php:37
PHP  15. Zizaco\Entrust\EntrustRole->attachPermission() /var/www/html/sac/database/seeds/DatabaseSeeder.php:68
PHP  16. Zizaco\Entrust\EntrustRole->perms() /var/www/html/sac/vendor/zizaco/entrust/src/Entrust/Traits/EntrustRoleTrait.php:92
PHP  17. Illuminate\Database\Eloquent\Model->belongsToMany() /var/www/html/sac/vendor/zizaco/entrust/src/Entrust/Traits/EntrustRoleTrait.php:35

**Comment by vivex** [comment]
Ok i solved the error myself,  i created new config file  config/entrust.php  and returned an array such as - 

return [
        'permission' =>'SAC\Entity\Permission',
        'role'=> 'SAC\Entity\Permission'
];


And it worked  :dancers:    you have define custom config if you are placing entities in other folder. :)
