### ISSUE TITLE
Entrust\HasRole: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by AlexDubstone** [Zizaco/entrust#224]
Hello, I'm getting an error using Entrust::can with version 1.3:

![image](https://cloud.githubusercontent.com/assets/6986114/5284345/cd2776e8-7b13-11e4-93dd-b623fab9e60f.png)

`$role->perms` is invalid. If I change it to $role->permissions it's working fine again. Is that a bug in 1.3?

**Comment by tuytoosh** [comment]
I have this issue . when i try `$role->permissions` it is not working yet

**Comment by AlexDubstone** [comment]
It was a bit confusing, because everything else I tried was working as I expected it, but the problem was (of course) on my side. Check that your Role and Permission models are extending EntrustRole and EntrustPermission, not Eloquent or your own Basemodel. And the User needs to use the HasRole trait. Then it should work as expected.

**Comment by tuytoosh** [comment]
is HasRole trait this : `use Zizaco\Entrust\Traits\EntrustUserTrait;`?

**Comment by tuytoosh** [comment]
now I have this error :
```
FatalErrorException in dashboardController.php line 15:
Call to a member function can() on a non-object
```

**Comment by tuytoosh** [comment]
my problem solved and if user is not logged in this issue was occurred.

thanks @AlexDubstone

**Comment by pedzed** [comment]
@tuytoosh Please close this issue if it's solved.

**Comment by tuytoosh** [comment]
@pedzed this is not my issue

@AlexDubstone

**Comment by pedzed** [comment]
> this is not my issue

Sorry, it seemed like you were the original poster. I should have double checked.
