### ISSUE TITLE
Laravel 5 Docs Note

### ISSUE THREAD

**Issue by csduarte** [Zizaco/entrust#228]
I know Laravel 5 is not currently supported, but the community are looking to use this great package and have found ways with your help. The issue about fixing the composer.json is fairly easy to find in the issues, but I had a hell of a time figuring out that I had to publish the config. Maybe we could just add it as note somewhere?

https://github.com/Zizaco/entrust/commit/0fc10dc5b24204d6c517131cc8f949bc053424bc

I'm new the open source game, so if I'm supposed to do it myself some where and pull request, please let me know...

Thanks!

**Comment by BrunoQuaresma** [comment]
@andrewelkins I think "fix" little things in my pull-request

**Comment by andrewelkins** [comment]
Please test with the [laravel-5](https://github.com/Zizaco/entrust/tree/laravel-5) branch
