### ISSUE TITLE
Entrust::routeNeedsRole not working

### ISSUE THREAD

**Issue by alisanie** [Zizaco/entrust#230]
I have link
http://localhost:8000/ad_register_product_brands 
And I want the only SuperAdmin and Admin can visit it, but  when I used 
Entrust::routeNeedsRole( '/ad_*',['SuperAdmin','Admin']);
every one can go to the page!
I add code to filters.app

**Comment by humbertoleite** [comment]
@alisanie you could solve?

**Comment by dschu-lab** [comment]
Have you tried it like this:
Entrust::routeNeedsRole( 'ad_*',['SuperAdmin','Admin']);

Without a '/' in the beginning? Also try it first with just one Role (i.e. Admin) and check if it works.

Hope it helps.

**Comment by alisanie** [comment]
Finally I found the solution
Entrust::routeNeedsRole( 'ad_*',['SuperAdmin','Admin'],Redirect::to('/'),false);
