### ISSUE TITLE
Get list of users that have permission?

### ISSUE THREAD

**Issue by eNzyOfficial** [Zizaco/entrust#238]
Is there an easier way to do it other than this?

```
    $permission = Permission::find(1);
    $users = array();

    foreach($permission->roles as $role)
    {
        foreach($role->users as $user)
        {
            $users[] = $user;
        }
    }
```

**Comment by Fneves7** [comment]
Hi, I have made a list that shows me all the users and their roles in labels, maybe it could help you if you adapt the code.

(if you clean the icons, labels and comments the code will become more simple)

<div class="box-body">
  <ul class="todo-list">
    @foreach($user as $user)
    <li>
      
      <span class=""><i class="fa fa-user"></i></span>

      
      <span class="text">{{$user->id. ' - ' .$user->name}}</span>

      
      @foreach($user->roles as $role)
        
        <small class="label label-info">
          <i class="fa fa-cog"></i> {{$role->name}}
        </small>
      @endforeach

    </li>
    @endforeach
  </ul>
</div>
