### ISSUE TITLE
Is there a way to test if a user has one role from a given list

### ISSUE THREAD

**Issue by rafaelmoraissantos** [Zizaco/entrust#239]
I came up with this, and I asked myself if theres a simple like this to test if a user has one of the roles:

```php
$user = Auth::user();

if ( ! $user->hasRole('Admin', 'Editor') ){

    App::abort(403, 'Access denied');

}
```
And this will return true if the user doesn't have any of these roles.

**Comment by nicekiwi** [comment]
See the Readme.md file, you can use the `ability` method:

    $user = Auth::user();

    if ( ! $user->ability('Admin', 'Editor', null) ){

        App::abort(403, 'Access denied');

    }

**Comment by andrewelkins** [comment]
That's correct
