### ISSUE TITLE
Shows Class 'App\' not found in Laravel 5

### ISSUE THREAD

**Issue by iftekhersunny** [Zizaco/entrust#241]
When I am trying to attach role with user it shows an error ( Class 'App\' not found ). In line number 18 of HasRole.php file, When I changed Config::get('entrust::role') to Config::get('entrust::role','Role') and Config::get('entrust::assigned_roles_table') to Config::get('entrust::assigned_roles_table','assigned_roles') it works fine.
Please solve this problem...

**Comment by bart** [comment]
This is possibly caused by the new Config::get method. I explained it in the Laracasts forum and will update my fork in the next hours so that you guys can use this instead.

**Comment by bart** [comment]
Updated fork, so you can use entrust with Laravel 5.0 as described here: https://github.com/Zizaco/entrust/issues/196

**Comment by iftekhersunny** [comment]
Bart thanks.

**Comment by andrewelkins** [comment]
For Laravel 5, Try the new [laravel-5](https://github.com/Zizaco/entrust/tree/laravel-5) branch.

**Comment by andrewelkins** [comment]
Updated the readme to include a reference to laravel-5 branch
