### ISSUE TITLE
Class '\Role' not found in laravel 5

### ISSUE THREAD

**Issue by tidusvn05** [Zizaco/entrust#247]
i have a problem as following:

* composer.json
"zizaco/entrust": "dev-laravel-5",

* i was run migration & can create roles, permission

* in model User, i made as guide from author:
<?php

use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Eloquent
{
    use EntrustUserTrait; // add this trait to your user model

    ...
}

then i attach role for an user:
$user->attachRole($admin); // parameter can be an Role object, array, or id
or $user->hasRole('admin');

=> i got an exception:

PHP Fatal error:  Class '\Role' not found in /Volumes/Data/IdooSources/ISAdminTools/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 971
PHP Stack trace:
PHP   1. {main}() /Volumes/Data/IdooSources/ISAdminTools/artisan:0
PHP   2. Illuminate\Foundation\Console\Kernel->handle() /Volumes/Data/IdooSources/ISAdminTools/artisan:36
PHP   3. Symfony\Component\Console\Application->run() /Volumes/Data/IdooSources/ISAdminTools/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:91
PHP   4. Symfony\Component\Console\Application->doRun() /Volumes/Data/IdooSources/ISAdminTools/vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   5. Symfony\Component\Console\Application->doRunCommand() /Volumes/Data/IdooSources/ISAdminTools/vendor/symfony/console/Symfony/Component/Console/Application.php:195

anyone can help me.

thank in advance!

**Comment by cjmling** [comment]
In the file u use 

$user->attachRole($admin); // parameter can be an Role object, array, or id
or $user->hasRole('admin'); 

Have u include below line at the top?

use App\Role;

**Comment by cjmling** [comment]
Just had the same issue

In entrust.php in config folder  change line  22

from 
'role' => '\Role',

to
'role' => 'App\Role'

**Comment by FDiskas** [comment]
Thanks @cjmling 
My Models is in App/Models directory and this Role model is within User directory so I changed the config 
```
'role' => 'App\Models\User\Role'
```
and now works - thanks to you

**Comment by ferrarif248** [comment]
Hello,

For Me this 2 options work great $user->attachRole($admin); or $user->hasRole('admin');

I have problem using on authanticated user hasRole() or can() function. If i use 
\Auth::user()->hasRole('role-name'); or \Entrust::hasRole('role-name'); which is the same i get allways this error: BadMethodCallException in Builder.php line 1991: Call to undefined method Illuminate\Database\Query\Builder::hasRole()

I create my own RoleAuthenticate in Middleware for checking if user is authanticated and if have a role and permission, but i get error above when checking function hasRole() or can() on authenticated user.

My User.php model is in app\Models folder. I also set up in composer.json 
<?php
namespace Nkralj\Models
use Zizaco\Entrust\Traits\EntrustUserTrait;
class User extends Eloquent
{
    use EntrustUserTrait; // add this trait to your user model
}
Also tried with User model like this
<?php
namespace Nkralj\Models
use Illuminate\Database\Eloquent\Model;
use Zizaco\Entrust\Traits\EntrustUserTrait;
class User extends Model
{
    use EntrustUserTrait; // add this trait to your user model
}

the error is the same..
composer: 
"autoload": {
		"classmap": [
			"database",
			"app/Models"
		],
		"psr-4": {
			"Nkralj\\": "app/"
		}
	},

and i also change in config/auth.php from 'model'=>'Nkralj\User' to 'model' => 'Nkralj\Models\User',

anyone have the same problem or can help me?

thank in advance!

**Comment by JessNielsen** [comment]
Instead of 
```php
Auth::User()->hasRole(), 
```
use:

```php
//Dependency injection to resolve user
public function __construct(User $user) {
    $this->user = $user
}

$userID = \Auth::id();
if ($this->user->find($userID)->hasRole('admin')) {

	//doSomething;

}
```
Entrust::hasRole() appear a bit broken to me, have yet to figure out why.

**Comment by tidusvn05** [comment]
@cjmling thank you!

**Comment by ferrarif248** [comment]
@JessNielsen thank you!

**Comment by JessNielsen** [comment]
Please close this issue if your problem has been resolved.

**Comment by callen5914** [comment]
None of those options fix the Role Not Found here...

**Comment by JessNielsen** [comment]
Well if you would elaborate on what your specific problem is, i might be able to assist you.

**Comment by callen5914** [comment]
I installed according to the specs found on the L5 readme. Then made a route to arbitrarily add a role and was greeted with a role not found error when using that route. 

That's when I found this Git Issue posting and changed to 'App\Models\Role' in the entrust.php file. 

I've tried multiple variations of the above declaration to no avail. Mind you I followed the instructions to the letter. 

I'm not sure if what I'm trying is a valid way of doing this. Normally I would build a seed. But I was experimenting with the ACL.

**Comment by callen5914** [comment]
Should the model extend model or EntrustRole? And if using in a controller what should be included? Also in the Config/Auth I'm not sure what key value pairs are needed if you publish as an option.

**Comment by JessNielsen** [comment]
If you havent changed the models directory the Role Model should be in **App/** not **App/Models/**.

In regards to the config, please post the setting for the user model and role model files.
you should extend the role model from EntrustRole, as the docs state.

Could you post the route code in question, and is it the Role table that isnt beeing found, or the model (Role.php)?

**Comment by joetann** [comment]
**[Fix suggested at bottom of this post]**

Hi. I had the same problem as @callen5914. I was 100% sure I've followed the instruction exactly as they are presented. I had no issues with Entrust in Laravel 4.x, but am with Laravel 5. This led me to believe that there was some step(s) required for Entrust in L5 that wasn't required in L4.

In my controller I had for example:

    <?php namespace App\Http\Controllers;
    use App\Models\Role;
    class WelcomeController extends Controller {
        public function index()
        {
            $owner = new Role();
            $owner->name         = 'superadmin';
            $owner->display_name = 'Super Admin'; // optional
            $owner->description  = 'The highest level of admin-ness'; // optional
            $owner->save();
        }
    }

All of my models were setup exactly as required in the usage instruction docs.

The problem was that my Role.php model (in my case located at /app/models/role.php) did not have a namespace declaration.

**Fix**

Make sure that your Role.php model looks like this, if for example you've moved your models into the /App/Models directory:

    <?php namespace App\Models;
    use Zizaco\Entrust\EntrustRole;
    class Role extends EntrustRole
    {
	
    }

Hope that helps.

**Comment by callen5914** [comment]
Holy Cow! Thanks a Heap!

This got it working as described! Maybe the documentation could use a little help on this one...

@joetann Thanks for saving the day!

**Comment by yahyazini** [comment]
Thanks @cjmling. That fixed it for me!

**Comment by natar10** [comment]
@joetann YEAH!

**Comment by alditis** [comment]
Thanks @joetann !!!

**Comment by alejandrofloresm** [comment]
In case someone has still this error I solved by:
1. Locate the configuration file of entrust, in my case it was on `vendor/zizaco/entrust/src/config/config.php`.
2. Save it as entrust.php on `App/config`. You'll end up with `App/config/entrust.php`.
3. In this file (entrust.php) change the settings so each model points to the location of your model.

**Comment by dibakarray** [comment]
I am using Laravel 5.2 and have the same problem, that is
FatalThrowableError in Model.php line 956:
Class 'App\Role' not found
I just put a name space at the top of Role Class
namespace App;

now it works.

**Comment by Goldilockszany** [comment]
@dibakarray wow. that works. thank you so much.
