### ISSUE TITLE
Using hasRole with Auth::user()

### ISSUE THREAD

**Issue by dylanglockler** [Zizaco/entrust#260]
I'm simply trying to check if a user has a Role, I can access hasRole if I find the user with the user model:

    $user = \App\Models\User::find( \Auth::user()->id );
    echo($user->hasRole('admin'));

The above returns 1. However if I try doing so directly with Auth::user();

    $user = \Auth::user();

I get the error below. From the instructions I thought the latter should work. If I have to use the former, is there a best practice for loading up the logged in user and passing it to all authenticated pages?

ErrorException in Builder.php line 1992:
Call to undefined method Illuminate\Database\Query\Builder::hasRole() (View: /Users/dylanglockler/Sites/laravel-lovelaundry-5/resources/views/layouts/admin.blade.php) (View: /Users/dylanglockler/Sites/laravel-lovelaundry-5/resources/views/layouts/admin.blade.php)

**Comment by dylanglockler** [comment]
I'm surprised no one else is having this issue. I was really hoping to use 

   @if(\Auth::user()->hasRole('admin'))

to check for admin privileges but it doesn't work.

**Comment by dylanglockler** [comment]
Found the issue..

in auth.php I had

    	'model' => 'App\User',

My namespace requires

    	'model' => 'App\Models\User',

**Comment by andrewelkins** [comment]
Nice!

**Comment by dylanglockler** [comment]
Once I'm logged in that works swimmingly. However if I leave that in the config/auth.php I get the error below on login. So at the moment, I have to change that config option to login then change it back to be able to access hasRole once I'm logged in!

```
ErrorException in EloquentUserProvider.php line 106:
Argument 1 passed to Illuminate\Auth\EloquentUserProvider::validateCredentials() must be an instance of Illuminate\Contracts\Auth\Authenticatable, instance of App\Models\User given, called in /Users/dylanglockler/Sites/laravel-lovelaundry-5/vendor/laravel/framework/src/Illuminate/Auth/Guard.php on line 383 and defined
```

**Comment by pedzed** [comment]
Do you still have problems? If not, please tell us how you solved it and close this issue.

**Comment by brili** [comment]
in config->auth.php set 'driver' => 'eloquent' instead of database
