### ISSUE TITLE
How to use Entrust in Laravel 5

### ISSUE THREAD

**Issue by vertoo** [Zizaco/entrust#262]
Hi, I'm new in Laravel and probably use Entrust in wrong way. Or maybe this package isn't ready for L5 yet?
I create question on stackoverflow: http://stackoverflow.com/questions/29047820/laravel-5-entrust-check-roles-not-working/29069047#29069047
In short here:
Why this not works?
```php
// middleware.php
\Entrust::hasRole('superadmin'); // => true
\Entrust::routeNeedsRole('admin/dashboard', ['superadmin'], abort(403, 'Forbidden'), false); // display 403 page
```
When I try change first parameter from 'admin/dashboard' to something else 403 page is displayed too. All steps from readme taken, admin panel for roles/permissions works good with attachRoles etc.

**Comment by thangngoc89** [comment]
Are you using L5 branch?

**Comment by vertoo** [comment]
Yes. 
` "zizaco/entrust": "dev-laravel-5",`

**Comment by andrewelkins** [comment]
Master is now on Laravel5
