### ISSUE TITLE
Move Latest Version to Master Branch

### ISSUE THREAD

**Issue by vinkla** [Zizaco/entrust#265]
Moving the latest version to the `master` branch and adding a branch alias to `composer.json` will allow developers to fetch the latest version by the the correct version number through its alias.

```json
"extra": {
	"branch-alias": {
		"dev-master": "2.0-dev"
	}
}
````
Instead of requiring the new Laravel 5 version like this:

```json
"zizaco/entrust": "dev-laravel-5"
```
Then developers can download specify the dev version like this:
```json
"zizaco/entrust": "2.0.*@dev"
```

I would also suggest creating a branch called `1.0` for all versions under `1.*`.

You could look at this [Instagram package](https://github.com/vinkla/instagram) for reference.

**Comment by andrewelkins** [comment]
Done. Moved to master and created a branch for L4 version, 1.0

**Comment by vinkla** [comment]
Great!
