### ISSUE TITLE
PHP Fatal error:  Class 'Zizaco\Entrust\EntrustServiceProvider' not found

### ISSUE THREAD

**Issue by donttalktorobots** [Zizaco/entrust#270]
Hello, I am trying to push some updates to Heroku after installing Entrust locally and I am getting the following error:

` Generating optimized autoload files
remote:        PHP Fatal error:  Class 'Zizaco\Entrust\EntrustServiceProvider' not found in /tmp/build_81cea6c9c6f9c44424750661a3bee17a/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 150
remote:        
remote:        
remote:                                                                   
remote:          [Symfony\Component\Debug\Exception\FatalErrorException]  
remote:          Class 'Zizaco\Entrust\EntrustServiceProvider' not found `

I am new to Laravel and can't seem to find what is going on.  I know Heroku is running composer when you push changes, and I have tried composer dump-autoload and composer update and nothing seems to work.

**Comment by donttalktorobots** [comment]
Fixed the problem, moving the package from "require-dev" to "require" allowed composer to run correctly. Found the answer here: http://stackoverflow.com/questions/28266778/laravel-5-deployment-to-heroku-error-output-php-fatal-error-class-not-found-i

**Comment by shraddhabanerjee** [comment]
I am getting the same issue, the package is already present in require section. Also done the composer update.

$ php artisan vendor:publish
PHP Fatal error:  Class 'Zizaco\Entrust\EntrustServiceProvider' not found in /var/www/vurtax/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146


                                                           
  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'Zizaco\Entrust\EntrustServiceProvider' not found
