### ISSUE TITLE
Class "\Role" or "\Permission" not found

### ISSUE THREAD

**Issue by uibar** [Zizaco/entrust#271]
Hello,

I was writing a command an Artisan Command and inside the handle method i used stuff like:
    if ($user->hasRole($role->name)) { ... }
and
    if ($role->users()->count() > 1) { $role->delete(); ... }

For the hasRole method I was getting FatalErrorEx
    Class '\Role' not found
and for the $role->delete() part I was getting
     [Symfony\Component\Debug\Exception\FatalErrorException]
     Class '\Permission' not found

I got it working by adding 
        'Role' => 'App\Role',
        'Permission' => 'App\Permission',
inside my app.php config file but it should not be the right way to do this.

Using Laravel 5.

**Comment by thangngoc89** [comment]
It is the right way to make it work. It's a namespace related thing

**Comment by stefanzweifel** [comment]
Instead of adding it to `app.php` you could add the following lines to your artisan command:

```php
<?php namespace App\Console\Commands;

use App\Role as Role;
use App\Permission as Permission;

class YourCustomCommand extends Command {
    
    ...

}
```

[This article](https://mattstauffer.co/blog/laravel-5.0-directory-structure-and-namespace) explains the Laravel 5 namespacing pretty good.

**Comment by uibar** [comment]
Yeah thank you. But still why dose it occur? If using it anywhere else its working without referencing the classes.

**Comment by uibar** [comment]
Hey, @stefanzweifel ! Just tested it out and it's not working for me...

still getting this exception even with them referenced in the file:
```php
<?php namespace App\Console\Commands;

use App\Role as Role;
use App\Permission as Permission;

//...result in console...
[Symfony\Component\Debug\Exception\FatalErrorException]
Class '\Role' not found
```

referencing in config/app.php is still the only workaround.

btw... I'm getting this exception only when my script gets to execute the following lines
```php
if (!$user->hasRole($role->name))
            $user->attachRole($role);
```
and here is the $user var: 
```php
$user = User::where('email', '=', env('ROOTMAIL'))->first();
```

**Comment by stefanzweifel** [comment]
Hm, that's strange.

Maymbe something with the relations is wrong. While I transition between Laravel 4 and 5 apps I often had such errors, because I forgot to add the fullpath to the `belongsTo()` relationship method.

Maybe the paths / namespaces to your `Roles` and `Permissions` models in [config.php](https://github.com/Zizaco/entrust/blob/master/src/config/config.php) are wrong? Have you set an application name with `php artisan app:name`?

I don't have an installation with entrust in my range, so I couldn't test it.

**Comment by uibar** [comment]
Thank you @stefanzweifel !

Indeed you are right. I forgot to set the correct model in config/entrust.php after publishing it.

I changed the default values from 
```php
    'role' => '\Role',
    'permission' => '\Permission',
// CHANGED TO:
    'role' => 'App\Role',
    'permission' => 'App\Permission',
```

And now it work with no problem. Noticed this when I looked inside the trait at the roles function:
```php

{
    /**
     * Many-to-Many relations with Role.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function roles()
    {
        return $this->belongsToMany(Config::get('entrust.role'), Config::get('entrust.role_user_table'), 'user_id', 'role_id');
    }
```

Thank you! Now I can close this.
