### ISSUE TITLE
Use Entrust on Controller

### ISSUE THREAD

**Issue by rebornishard** [Zizaco/entrust#280]
I tried to use Entrust to check rules on controller, but it give me :  
```
Call to a member function hasRole() on a non-object
```
this is what i did in controller :  
```php

            $user = Confide::user();
            $user = $user->username;
            if($user->hasRole('Admin')) {
                $test= 'hello';
            }
```
  
another approach give me :  
```
Call to undefined method Illuminate\Database\Query\Builder::hasRole()
```
this is what i did in controller :  
```php

            $user = Confide::user();
            if($user->hasRole('Admin')) {
                $test= 'hello';
            }
```
  
is this possible or not to check role in controller ?  
or i did it wrong ?
thanks

Use :  
Laravel 4.2
Confide
Entrust 1.3

**Comment by rebornishard** [comment]
ok sorry , this one solved, i didn't realize master branch for laravel 5
here what i do now
```php
            Auth::check();
            $user_data = Confide::user();
            $user = Users::where('username', '=', $user_data ->username)->first();
```
do i need to Auth::check() ?
thanks

**Comment by minkbear** [comment]
Why did you use something like this? https://github.com/Zizaco/entrust/issues/260#issuecomment-83777477

\Auth::user()->hasRole('admin')

**Comment by rebornishard** [comment]
i didn't use it, only use : 
```php
$user_data = Confide::user();
            $user = Users::where('username', '=', $user_data ->username)->first();
```
am i do it wrong ?  
and is there any sample to use this with routes which referring to function from controller ?
thanks

**Comment by Prophet731** [comment]
Did you add the HasRole trait to your Users model?
