### ISSUE TITLE
Where do I generate the application roles & permissions?

### ISSUE THREAD

**Issue by thomasfw** [Zizaco/entrust#284]
**Where are people creating their roles and permissions?**

For example, the following creates a new admin role and adds a permission in the database, and only needs to be run once - 

```php
$admin = new Role();
$admin->name  = 'admin';
$admin->save();

$createPost = new Permission();
$createPost->name = 'create-post';
$createPost->save();

$admin->attachPermission($createPost);
```

Presumably there is somewhere I can be defining my roles and permissions once? What is the recommended procedure here?

**Comment by thomasfw** [comment]
To clarify, I want to assign a predefined role to a user on signup. Obviously I don't want to place the code to define roles/permissions in my signup logic, and as far as I can tell the code to define the roles/procedures only needs to be run once. Should I create an event?

**Comment by thomasfw** [comment]
I've gone with creating a seeder to define the roles and permissions...

```php
class RolesTableSeeder extends Seeder 
{
    public function run()
    {
        DB::table('roles')->delete();

        $admin = new Role();
        $admin->name  = 'admin';
        $admin->save();
        ...
```
If there's a better way to do this i'm keen to know it.

**Comment by lijinma** [comment]
It would be better to create roles and permissions in migrations. Because it's not good for you to add db seeds for production environment.

**Comment by thomasfw** [comment]
I've gone with a seeder instead of migrations as I personally use migrations for schema.

For anyone who's interested, i've created a Seeder class that will allow you to manage your Roles & Permissions in one place. From here you can add/update/remove roles and assign permissions to them. The seeder will re-etablish relationships between users, roles and permissions.

**RolesAndPermissionsSeeder**
https://github.com/thomasfw/RolesAndPermissionsSeeder

**Comment by bgies** [comment]
Just had a look at your seeder class... it looks very useful... Thanks.

**Comment by jrm2k6** [comment]
Thanks for answering this. A seeder was my idea also, nice to see it is the way to go.
Migrations shouldn't contain data to insert, migrations are in charge of modifying schemas, not content.
