### ISSUE TITLE
Update a role

### ISSUE THREAD

**Issue by gringo-m** [Zizaco/entrust#286]
What is the prefered method to update roles ?

When I try to attach a new role to a user that already has one, I get :  
Integrity constraint violation: 1062 Duplicate entry

**Comment by thomasfw** [comment]
Try this seeder class - you can add/update/remove roles in one place without breaking relationships between users, roles and permissions.

**RolesAndPermissionsSeeder**
https://github.com/thomasfw/RolesAndPermissionsSeeder

**Comment by jrm2k6** [comment]
And what if you don't want to use a seeder?
Shouldn't it be as easy as getting a user, removing the role, adding the new one? I am open to do it, but we are still using laravel4.2 at my company.
@andrew13 opinion?
