### ISSUE TITLE
$user->roles()->attach($admin->id) returns NULL

### ISSUE THREAD

**Issue by wahidsherief** [Zizaco/entrust#289]
I tried to attach roles to my admins. I followed all the steps carefully and did able to create rows  in Role table in db with data. but when i tried to assign role using, $user->roles()->attach($admin->id) it returns Null. How can i fix it ?

**Comment by tuytoosh** [comment]
try this `$user->attachRole($admin);`

**Comment by wahidsherief** [comment]
tried with $user->attachRole($admin); also .. but it didn't help. now I fix it by -

    $user->attachRole($admin->id);

now working great

**Comment by tuytoosh** [comment]
if `$admin = new Role();` it works...

I am now using this package...

**Comment by wahidsherief** [comment]
I also used    $admin = new Role(); but in my case not happened, it returns null in both case mentioned here. So i tried my stuff then it works. BDW thanks for reply !!
