### ISSUE TITLE
$admin->attachPermission($createPost) 

### ISSUE THREAD

**Issue by tarunhere** [Zizaco/entrust#290]
I have implemented entrust, but I have admin table instead of User. User table is also there, but I don't want to use that for admin. I have create the database and trying to attach permission in permission_role table with this method in *tinker* and I am getting this error.

 >BadMethodCallException with message 'Call to undefined method Illuminate\Database\Query\Builder::attachPermission()'

In EntrustUserTraits.php I have changed column from user_id into admin_id. What other changes might require here to use Entrustpermission??

I am a novice and just trying with entrust to implement roles and permission. Any help/idea appreciated a lot. Thanks

**Comment by gbelot2003** [comment]
I got the same error from tinker!!!

**Comment by pedzed** [comment]
`undefined method` means that it cannot be found. Do you actually make use of the trait?

**Comment by anandatheerthan** [comment]
I too get the error while trying to attach permission to user. My User model extends Model though.

**Comment by pedzed** [comment]
> I too get the error while trying to attach permission to user. My User model extends Model though.

That's fine, it's all about the trait. Do you have PHP 5.4+ and did you add the following?
```php
class User extends Model implements AuthenticatableContract, CanResetPasswordContract
{
    // ...
    use EntrustUserTrait;
    // ...
}
```

**Comment by anandatheerthan** [comment]
I have PHP 5.6 and using below in User model
use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract {

	use Authenticatable, CanResetPassword;
	use EntrustUserTrait; // add this trait to your user model

**Comment by anandatheerthan** [comment]
My mistake, I was trying to use attachPermission on User instance rather than Role. It is working now after i use $role->attachPermisson($create-permission)

**Comment by pedzed** [comment]
@tarunhere Please, close this issue if this issue is resolved.

**Comment by tarunhere** [comment]
yes... its resolved. thanks @pedzed
