### ISSUE TITLE
Unable to create "entrust.php"

### ISSUE THREAD

**Issue by gildniy** [Zizaco/entrust#295]
Hello, I am building an app based on L5 (I use Laravel 5.0.28 version and am not a pro-developer though), but when I try to install Zizaco/entrust, as described in the Tuto, after including "zizaco/entrust": "dev-laravel-5" in composer.json and run "composer update" when trying to run the command "php artisan vendor:publish", the file "entrust.php" in "(my_app_name)/config/" folder is not generated. And once I run "php artisan entrust:migration" I get the error:

"C:\xampp\htdocs\(my_app_name)>php artisan entrust:migration
  [InvalidArgumentException]
  There are no commands defined in the "entrust" namespace."

Can any one tell me what I can do!?

**Comment by gildniy** [comment]
I thing the problem is that my "artisan service" doesn't recognize the "Zizaco/entrust" package even if I registered it in the app.php service providers. What can be the reason for this issue? Or can you suggest which other reason for my problem?

**Comment by gildniy** [comment]
I found the Migration Setup file here: https://github.com/Zizaco/entrust/blob/master/src/views/generators/migration.blade.php but I still need a convenient answer. Still waiting thanks in advance.

**Comment by gildniy** [comment]
Solved, I downloaded a freshy copy of L5 and replaced all files which I was changed. It's a though task, but finally, it worked!

**Comment by billmn** [comment]
Can you close this issue?

**Comment by gildniy** [comment]
Fixes #295
