### ISSUE TITLE
Edit Permission a role From checked checkbox

### ISSUE THREAD

**Issue by m-alinasab** [Zizaco/entrust#299]
Hello.

I got this package installed.

I create access privileges to each role than I did.
Now I want to change the permissions for each role.

How can all permissions a role access and selected cases also revealed?

For Example : 
All Permission : 
post_manager  ,  post_create  , post_edit  , post_delete  , user_manager , user_create

And permissions  Role "owner" is :
post_manager , post_edit

now , Edit "owner" permision Via checkbox , for Example :  
Add Permission : 
http://up.vbiran.ir/uploads/1845914310035203725_perm-add.png

Edit Page For Permission : 
http://up.vbiran.ir/uploads/38084143100351932546_perm-edit.png

Please Help me .

Thank You :)

**Comment by Zizaco** [comment]
I didn't get your question, but I think entrust is pretty capable of doing what you need. (I personally use an interface like you described)
