### ISSUE TITLE
[Question] Does this package support organization-specific roles?

### ISSUE THREAD

**Issue by bkuhl** [Zizaco/entrust#303]
For my project, I need roles to be granted to users with addition pivot/meta data... specifically an `organization_id`.  A user may be an `Admin` on Organization A but not be an admin on Organization B.  Is this possible with this package?  From looking at the Role trait I don't see any parameters for additional metadata to be checked.

**Comment by jamesaspence** [comment]
Curious about this as well. I have an exact similar situation to @bkuhl, except that it can go further into a third tier. This seems to be more global-based permissions.

**Comment by bkuhl** [comment]
I've done some research in this space and it doesn't appear as though there are any packages that support this kind of scenario out of the box.

**Comment by jamesaspence** [comment]
https://github.com/cartalyst/sentry seems to support user groups. I'm looking into using those to specify permissions.

**Comment by andrewelkins** [comment]
I think Sentry's groups parallel Roles in our terminology.

**Comment by bkuhl** [comment]
@jamesaspence - Sentry doesn't yet support L5 and is a bit overkill for what I need at the moment.

@andrewelkins - I'm not sure I'm following what you mean with "parallel Roles in our terminology".  Can you please elaborate?

**Comment by lvandyk** [comment]
Has this been solved yet? We also have a situation where a user can be an admin on Org A and a standard user on Org B.

**Comment by APaquette** [comment]
Out of the box, it doesn't look like this is possible, but with some tweak it would certainly be possible. I'd probably recommend an array in a user field 'isAdmin' or something of that effect and then have the id's of the organizations in there. If they have an isAdmin array value that contains the ID of the group, they have the necessary permissions to perform the various tasks. Just by looking at what is available here it would be possible to do relatively easily as well but not with only what has been provided.
