### ISSUE TITLE
Tag a version for Laravel 5

### ISSUE THREAD

**Issue by freekmurze** [Zizaco/entrust#305]
Hi,

could you tag a working L5 version so we don't have to target a dev branch to pull the package in?

**Comment by joselfonseca** [comment]
+1 for that one! thanks @freekmurze

**Comment by bcat-eu** [comment]
+1

**Comment by mathev19** [comment]
+1

**Comment by Zizaco** [comment]
Absolutely! I'll take a look at the code tonight and create that tag. : )

**Comment by freekmurze** [comment]
:tada:

**Comment by Zizaco** [comment]
Tag created `1.4.0`

**Comment by Zizaco** [comment]
Also added a badge to tell which version is the latest
