### ISSUE TITLE
Entrust::hasRole() gives error

### ISSUE THREAD

**Issue by faifuhi** [Zizaco/entrust#309]
In my controller method, I've this bit of code:

if(Entrust::hasRole('admin'))
{ return 'Great! you have the role';}
return 'Sorry! not allowed';

But it returns the following error:
Non-static method Zizaco\Entrust\Entrust::hasRole() should not be called statically, assuming $this from incompatible context

What am i doing wrong?

**Comment by Zizaco** [comment]
It seems that you have not registered the Entrust 'alias' in the facades array of your config files

**Comment by faifuhi** [comment]
in config/app.php, I've the following in aliases array:

'Entrust'   => 'Zizaco\Entrust\EntrustFacade'

But i still get the error.

**Comment by saimiris** [comment]
I get the exact same error. Could anybody solve it?

**Comment by saimiris** [comment]
Solved. You have to remove the "use Zizaco\Entrust\Entrust;" call on the top of your file.

**Comment by Yarandi** [comment]
@faifuhi
Hi , i get below error when i want to get current logged in user's role and permissions with this method:
`Entrust::hasRole('role-name')` OR `Auth::user()->hasRole('role-name');`

i followed exactly installation instruction but i get below error :
`Non-static method Zizaco\Entrust\Entrust::hasRole() should not be called statically`

How did you solve the problem?

**Comment by finchy70** [comment]
I have a similar problem.  I'm trying to return an array of users that have a role called 'user' set up for.
The code I'm running is
`$users = User::hasRole('user')->get();`

Get the same User::hasRole() should not be called statically.

What am I doing wrong?

**Comment by RomkaLTU** [comment]
Same here.

**Comment by erickcg** [comment]
bump, why is this closed? I am having the same problem

**Comment by Benyaminrmb** [comment]
@Yarandi  
I have the same error 

**But do you really use this** `Auth::user()->hasRole('role-name');` **in your code?**

Look i try
 `echo Auth::user()->hasRole('admin');` 
And Work , its show me `1` 

> maybe we must use this way until someone solve `Entrust::hasRole('role-name');`

**Comment by vineeth030** [comment]
When I replace "use Zizaco\Entrust\Entrust;" with "use Entrust" it worked for me.
