### ISSUE TITLE
Implement middleware permissions check

### ISSUE THREAD

**Issue by poma** [Zizaco/entrust#316]
It would be nice to implement middleware to specify required permissions directly in routes:

```
Route::group(['prefix' => 'admin', 'middleware' => ['role:admin|root']], function() {
	Route::get('/', 'AdminController@welcome');
	Route::get('/manage', ['middleware' => ['permission:manage-admins'], 'uses' => 'AdminController@manageAdmins']);
});
```
Laravel 5.1 LTS [will be released in a few days](https://github.com/laravel/laravel/commit/41472b79dbe1d7eda67357632944984555cf858c#commitcomment-11225456) and it [supports passing parameters to middleware](https://laravel-news.com/2015/04/laravel-5-1/). Meanwhile we can emulate this functionality on 5.0 (just for reference)

```
Route::group(['prefix' => 'admin', 'roles' => 'admin|root'], function() {
	Route::get('/', 'AdminController@welcome');
	Route::get('/manage', ['permissions' => 'manage-admins', 'uses' => 'AdminController@manageAdmins']);
});
```

Corresponding implementations for this feature would be pretty simple:
```php
class EntrustPermission {

	/**
	 * Handle an incoming request.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @param  \Closure $next
	 * @param null $permissions
	 * @return mixed
	 */
	public function handle($request, Closure $next, $permissions = null)
	{
		if ($permissions != null && !\Auth::user()->can(explode('|', $permissions))) {
			return response('Forbidden', 403);
		}

		return $next($request);
	}

}
```

and for 5.0 example (you need to include this middleware globally):
```php
class EntrustPermission {

	/**
	 * Handle an incoming request.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  \Closure  $next
	 * @return mixed
	 */
	public function handle($request, Closure $next)
	{
		$action = $action = $request->route()->getAction();

		if (array_key_exists('permissions', $action) 
			&& !\Auth::user()->can(explode('|', $action['permissions']))
		) {
			return response('Forbidden', 403);
		}

		return $next($request);
	}
}
```

**Comment by damienIN** [comment]
@Zizaco with the new implementation of Middleware Parameters, this would be a really simple way to implement route filters, with Route::filter() being deprecated in Laravel 5 for the new middleware implementation.

**Comment by AlexanderPoellmann** [comment]
+1 from me!

**Comment by silentFred** [comment]
+1 here too =)

**Comment by unitedworx** [comment]
This looks like a very clean way of adding permissions throughout your app!!!!!

Does the above sample code work in 5.1? I want to use this method for checking permissions thought my routes rather than in each controller method! Or using filters that are deprecated!

**Comment by poma** [comment]
Yes. I provided 2 separate examples for 5.0 and 5.1

**Comment by unitedworx** [comment]
Thanks for the reply poma, I figured this is a full working code, will Probably modify it a bit to use ability() method instead on can() so it's a bit more flexible

This should be part of entrust code/examples if you ask me! Instead of the deprecated filters

**Comment by poma** [comment]
Created a pull request with added `ability` middleware and updated documentation. Code still requires some testing because I don't have a chance to run it at the moment.

**Comment by unitedworx** [comment]
wow! nice work @poma hopefully this will be pulled in. i am in the process of upgrading my project to 5.1 and once i do i will certainly try this out and let you know if i see any issues.

Although i feel that pipe | should be used for separating parameters and comma for separating individual roles/permissions to keep this consistent on how ability works ! e.g middleware' => ['ability:admin,owner|create-post,|edit-user|true'] a bit more readable i think and a bit more consistent on how ability works with commas $user->ability('admin,owner', 'create-post,edit-user');

i will probably shoot a pull request to improve can() and hasRole() a bit to get them in line with the ability method so they can accept commas as well since its cleaner than an array. e.g $user->can($user->can('edit-user,create-post')

**Comment by poma** [comment]
@unitedworx Comma is reserved by Laravel to separate middleware parameters so we can't use that. Also if you are going to modify can we probably should `trim()` name before comparing it to allow space after commas/pipes for better readability.

**Comment by unitedworx** [comment]
I am now using this middleware to check for permissions in my project and works well, although I modified your version in the pull request since it failed if there was no logged in user! I had to pull in the auth guard and check if it's not a guest user first before doing user()->can !! Cozy if you don't have a logged in user then you don't have a user to check up on their permissions.

Here is what I am using

```
entrust middleware

    <?php namespace App\Http\Middleware;
    use Closure;
    use Illuminate\Contracts\Auth\Guard;
    class EntrustPermission
    {
	protected $auth;
	public function __construct(Guard $auth)
	{
		$this->auth = $auth;
	}
	public function handle($request, Closure $next, $permissions)
	{
		// if its not a guest then check to see if user has specified permissions
		if  ( (!$this->auth->guest()) 
			&& ($request->user()->can(explode('|', $permissions))) ) {
				return $next($request);
		}
		// if its an ajax call then return a json response
		if ($request->ajax()) {
                    return response('Unauthorized', 401);
       		}
        	// redirect to home when not autorized.. or you can do: abort(403);
     		 else  {	
          	    return redirect('/');
     		   }            
	}
    }

```

**Comment by poma** [comment]
Added guest support to my pull request. We try to avoid returning any responses from third party libraries. Instead libraries should throw exceptions and then exception handler will decide how to handle them and what should be returned to user.

**Comment by unitedworx** [comment]
nice to see that updated many many thanks for the info. I looked into abort and realized that its basically raising an exception which i can catch in my exception handler and do any redirection or return a response for ajax requests in there! Which is cool! :) learning new things every day and keep refactoring things for the better!

**Comment by Imekhan** [comment]
@poma i'm using can as may method, which is working fine for one permission check like
Auth::user()->may('global')
but not working when i give array data like: 
Auth::user()->may('create-user|edit-user|delete-user');
please suggest;

**Comment by kabircse** [comment]
How to set default all permission for a user like root ?
