### ISSUE TITLE
Get the roles of an user

### ISSUE THREAD

**Issue by Arend-Jan** [Zizaco/entrust#319]
I can't get my head around it. How can I get all the roles from a specific user?

My solution so far doesn't work. What aim I doing wrong?

```php
Route::get('/sometestroute', function() {
    $user = App\User::find(1);
    foreach($user->roles() as $role)
    {
        echo $role;
    }
}
```
simplified tabel content
--- users ---

| id  | name  | some more stuff |
| :------------ |:---------------|:-----|
| 1      | arend-jan | some more values |

--- roles ---

| id  | name  | some more stuff |
| :------------ |:---------------|:-----|
| 1      | admin | some more values |

--- role_user ---

| user_id  | role_id  |
| :------------ |:---------------|
| 1      | 1 |

**Comment by Prophet731** [comment]
This is my way of doing it in L4. Should apply to L5 as well.

User Model
```PHP
<?php namespace Account;

use Illuminate\Support\Facades\Config;
use Zizaco\Confide\ConfideUser;
use Zizaco\Confide\ConfideUserInterface;
use Zizaco\Entrust\HasRole;

class User extends \Eloquent implements ConfideUserInterface
{
    use ConfideUser;
    use HasRole;

    /**
     * @return Illuminate\Database\Eloquent\Model
     */
    public function roles()
    {
        return $this->belongsToMany('Account\Role', Config::get('entrust::assigned_roles_table'));
    }
}
```
Role Model
```PHP
<?php namespace Account;

use Illuminate\Support\Facades\Config;
use Zizaco\Entrust\EntrustRole;

class Role extends EntrustRole {}
```

Dirty example. It's pretty much the same as what you're doing. The relationship in the user model pulls all roles that are assigned to the user.
```PHP
<?php

$user = User::with('roles')->find(1);

var_dump($user->toArray());
```

**Comment by Arend-Jan** [comment]
thanks Prophet731. This solved my problem.
