### ISSUE TITLE
Integrity constraint Violation

### ISSUE THREAD

**Issue by archer3cl** [Zizaco/entrust#321]
Fresh installation of Entrust on Laravel 5 and im trying to make a Seeder with the given Roles/Permissions on the Usage instructions and i get the following error
  

[Illuminate\Database\QueryException]
  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update
  a child row: a foreign key constraint fails (`fields_of_justice`.`permissio
  n_role`, CONSTRAINT `permission_role_permission_id_foreign` FOREIGN KEY (`p
  ermission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE ON UPDATE
  CASCADE) (SQL: insert into `permission_role` (`permission_id`, `role_id`) v
  alues (roles, 1))

My Set Up

```php
<?php
use Illuminate\Database\Seeder;
class PermissionTableSeeder extends Seeder {

    public function run()
    {
        $owner = new \App\Role;
        $owner->name         = 'owner';
        $owner->display_name = 'Project Owner'; // optional
        $owner->description  = 'User is the owner of a given project'; // optional
        $owner->save();

         $owner_user = \App\User::create([
            'username' => 'owneruser',
            'email' => 'maill@mail.com',
            'password' => 'somepassword'
        ]);
        $owner_user->attachRole($owner);
        
        $createTask = new \App\Permission;
        $createTask->name         = 'coe-task';
        $createTask->display_name = 'CoE Tasks'; // optional
        $createTask->description  = 'create or edit tasks'; // optional
        $createTask->save();
        $owner->attachPermissions($createTask);
      }
}
```

**Comment by archer3cl** [comment]
Im closing this issue. Such a lame mistake. 

I just didnt follow the instructions correctly so in the Permissions model i had  extends EntrustRole instead of extends EntrustPermission. So the permission i was trying to save was in Roles and thus i couldnt create the relationship.

Again sorry.

**Comment by paperscissors** [comment]
Might be a mistake, but glad you documented it. Absentmindedly did the same thing.
