### ISSUE TITLE
Best practice for building large navigation system

### ISSUE THREAD

**Issue by matbeard** [Zizaco/entrust#325]
I'm converting a large CodeIgniter app to Laravel 5.1 and I'm using Entrust.

I have a partial view for the app's main navigation menu, which needs to perform lots (about 20) of permission checks to determine which links to display. I imagine this is a common situation.

What's the best practice here? In CodeIgniter I was placing an array of the user's permissions in the session and then using that to build the menu. I don't want to add an additional 20 DB queries for every page.

Any tips? I can't be the only person facing this issue.

**Comment by wadephillips** [comment]
Entrust adds all the permissions to the User object automatically as well as methods for checking the permissions/ roles.


Here's what you need to do.
`$user = Auth::user();`
`$user->can('permission_foo');`
`//or`
`$user->hasRole('role_foo');`
`//put multiple permission/role checks in an array`
`$user->can(['permission_foo', 'permission_bar', 'permission_baz', 'etc']);`
`//or`
`$user->hasRole(['role_foo', 'role_bar', 'role_baz']);`

https://github.com/Zizaco/entrust#checking-for-roles--permissions

**Comment by matbeard** [comment]
Ah... okay. I get it. I can cope with a couple of quick DB queries to get all this functionality. Thanks
