### ISSUE TITLE
Configurations from auth.php have no effects

### ISSUE THREAD

**Issue by hiendv** [Zizaco/entrust#330]
My application namespace: **Acme**.

As it's mentioned in the documentation:
> Set the property values in the **config/auth.php**. These values will be used by entrust to refer to the correct user table and model.

I use **config/auth.php** without publishing entrust's config: `'model' => Acme\User::class`
It should be fine without any problems. But when it comes to relation methods, `roles()` for example, the `model` configuration from **config/auth.php** has no effect at all. Result in
> PHP Fatal error:  Class 'App\Role' not found

**Comment by cdarken** [comment]
Did you publish the vendor config file?
`artisan vendor:publish --provider='Zizaco\Entrust\EntrustServiceProvider'`
Then in config/entrust.php change App to Acme.

**Comment by hiendv** [comment]
I have to, according to the documentation, it's obviously optional though.

**Comment by cdarken** [comment]
Yes, but after that you still have that error?

**Comment by hiendv** [comment]
No, it's totally fine with vendor's configurations :smile:
