### ISSUE TITLE
how to filter user collection based on role attached?

### ISSUE THREAD

**Issue by sivajik34** [Zizaco/entrust#331]
I have 3 roles named "admin","merchant","customer"how to get user collection contain merchant role?

**Comment by ajarti** [comment]
+1   does one need a scoped query to filter?

**Comment by ajarti** [comment]
Ok figured it out, you use "whereHas" (http://laravel.com/docs/5.1/eloquent-relationships#querying-relations) in the query scope of your model.

```php
public function scopeAdmins($query)
    {
        return $query->whereHas('roles',function($q){
            $q->where('roles.name', '=', 'admin');
        });

    }
```
Probably better to match on ID's, you know how free text matching ends up (Kaboom!) .. hahah

You get all admins like this:

```php
\App\User::Admins()->get();
```

Hope that helps :)

**Comment by sivajik34** [comment]
thank you .
