### ISSUE TITLE
Functions to Get a User's Role and Permissions

### ISSUE THREAD

**Issue by lukedanielson** [Zizaco/entrust#34]
Are there functions within Entrust to get a $user objects roles and/or permissions?

I'm trying to print to screen what assigned role the user is and his/her associated permissions...

Thanks,

-Luke

**Comment by prionkor** [comment]
@darrylkuhn What is the path of the `HasRole` trait? I tried `use Zizaco\Entrust\Traits\HasRole;` but it is not there.
