### ISSUE TITLE
No implementation of Soft Deletes

### ISSUE THREAD

**Issue by hcancelik** [Zizaco/entrust#348]
There is no where on this package that implements Laravel soft deletes however the instructions has a section about "Soft Deletes". I think someone has confused with foreign keys and cascading vs soft deletes.

According to Laravel documentation in order to have Soft Deletes, Model needs to use SoftDeletes; and table needs to have "deleted_at" column.  

http://laravel.com/docs/5.1/eloquent#soft-deleting

**Comment by eagle-r** [comment]
There is actually code in there to check if the role (or permission) has turned on soft deleting and handle accordingly - see `EntrustRoleTrait`. You just have to turn on soft deleting in your role model.

However, note that this will not work in Laravel 5.1 or 5.2 at the moment, as the Laravel team renamed the `SoftDeletingTrait` (and the `bootSoftDeletingTrait` method which the code is dependent upon) to `SoftDeletes` (and `bootSoftDeletes` method).
