### ISSUE TITLE
Please update doc for Laravel 5.1

### ISSUE THREAD

**Issue by nasirkhan** [Zizaco/entrust#349]
The instruction on Readme is not updated for Laravel 5.1. Can you please update this doc?

**Comment by schonhose** [comment]
I second this. As a new user with laravel I find it hard to implement this in 5.1.

@nasirkhan Did you manage to get it working? If so, could you provide me with the information needed?

**Comment by hcancelik** [comment]
Currently I'm working on Laravel 5.1 and it works fine with the current documentation. What kind of information do you need?

**Comment by acacha** [comment]
@hcancelik not sure what @schonhose @nasirkhan wants but for example the README don't talk about Middleware. In Laravel 5.1 route filters are deprecated in preference of Middleware

**Comment by bgies** [comment]
For instance in the root/config/app.php file the Service Provider should be added as Zizaco\Entrust\EntrustServiceProvider::class although the declaration in the doc will also work.

**Comment by isbkch** [comment]
I had no problem following this on 5.1

**Comment by poma** [comment]
Right now declaration from the docs works for both 5.0 and 5.1 which is a good thing because some people haven't updated to 5.1 yet. As for middleware it is not implemented so it's not a problem with the docs. I already created Pull Request #357 for this so feel free to use it as patch until it's accepted.

**Comment by bgies** [comment]
Yeah, but I think some people will be confused by it... especially newbies, and most newbies will be downloading 5.1. When they look at the Laravel declarations and your declaration is very different, they will spend a lot of time trying to figure out why. 

The old declaration still works... but letting people know they can use the new one for 5.1 would be a good idea for clearer docs

**Comment by nasirkhan** [comment]
As many of you are saying that the doc is ok for Laravel 5.1. 
But i am not an expert like you, so i found some difference with the laravel official doc and this doc. at the same time i could not find any starter project where the Entrust is used for authentication. That is why i could not use this package.

I am interested to use this package and that is why i asked to update the doc so that i can easily implement it with my project.

**Comment by bgies** [comment]
@nasirkhan Can you tell us specifically what you need? That would help a lot to make the docs clearer

**Comment by nasirkhan** [comment]
I will let you know. 

I am not an expert in Laravel 5.1. I started a project and planned to use Entrust. But as i did not used this package earlier i tried to find some starter project first and read the doc. The problem was i could not find any starter project and could not meet all the features i wanted to use on my application. 

As all of you are saying the doc is ok, then previously i must missed something and now i am going to start a starter project and will knock you i need assistance.

**Comment by arafatx** [comment]
Please update and remove the predicated functions in laravel 5.1, Like the routing filter. This package is not well-documented for beginner who use Laravel 5.1+. Newbie here.

**Comment by martinsnajdr** [comment]
+1

**Comment by JFOC** [comment]
+1

**Comment by xitude** [comment]
+1

**Comment by tuwannu** [comment]
Waiting for Zizaco/entrust#357 to be merged in so we have middlewares ready for Laravel 5.1.

Then I can help with updating the docs.

**Comment by tuwannu** [comment]
[`::class` class name resolution was introduced in PHP 5.5+](http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class). Entrust [requires PHP 5.4.0+](https://github.com/Zizaco/entrust/blob/master/composer.json#L25).

Therefore the declaration should stay in quote format as it is to maintain compatibility until Entrust requires PHP 5.5.0+ or Laravel 5.1+.
