### ISSUE TITLE
Failure when running Laravel tests... runs fine in browser

### ISSUE THREAD

**Issue by bkuhl** [Zizaco/entrust#365]
Running a unit test and keep running into a function nesting level error.

`Fatal error: Maximum function nesting level of '100' reached, aborting! in /path/to/project/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1057`

Here's my test:

```
    public function setUp()
    {
        parent::setUp();

        $this->headCoach = User::where('email', DatabaseSeeder::HEAD_COACH_EMAIL)->first();
    }

    /**
     * @test
     */
    public function viewRoster()
    {
        $this->actingAs($this->headCoach)
            ->visit('/roster')
            ->see('Player Roster');
    }
```

Here's where it's failing:
```
@if(Auth::user()->hasRole('head-coach')
```

Should this functionality be working or is this a known issue?

**Comment by bkuhl** [comment]
This seems to be something underlying with Laravel.... adjusting the max_nesting_level to 500 resolved it for me.  See https://laracasts.com/discuss/channels/general-discussion/l5-maximum-function-nesting-level-of-100-reached-aborting

**Comment by jhoff** [comment]
Pretty alarming that checking the permission or role of a user requires over 100 nested functions. Seems like a red flag...

**Comment by bkuhl** [comment]
Yeah... I think it's an underlying issue with something in Laravel because people have experienced it somewhat regularly outside of using this package.  I don't like the idea of increasing the nesting level, but I also don't think it's an issue with the Entrust package.
