### ISSUE TITLE
How to use it with Laravel Authentication

### ISSUE THREAD

**Issue by kadnan** [Zizaco/entrust#368]
How can I use *Entrust* routes with Laravel Authentication routes as given in manual:

```
Route::get('profile', ['middleware' => 'auth', function() {
    // Only authenticated users may enter...
}]);

// Using A Controller...

Route::get('profile', [
    'middleware' => 'auth',
    'uses' => 'ProfileController@show'
]);
```

**Comment by Gummibeer** [comment]
I don't get your main-problem!? What do you want to get as the result?
Do you want to protect a Route for a specific role/permission or what?

**Comment by kadnan** [comment]
How can I use something given below with Laravel's basic authentication system?
```
Entrust::routeNeedsRole('admin/advanced*', 'owner', Redirect::to('/home'));
```

**Comment by Gummibeer** [comment]
Do you mean your ```Authenticate``` Middleware? If yes than just extend the ```handle()``` with something like this:

```php
if($request->is('admin/advanced*') && !$this->auth->User()->hasRole('owner')) {
    return redirect()->to('home');
}
```
But you can write your own middleware for a cleaner code and usage.

It's not tested but should work. You also can extend the constructor of the Controller wich handles this route.
Or use the Laravel Route class with filters:
```php
Route::filter('owner_role', function()
{
    if (!Entrust::hasRole('owner')) {
        App::abort(403);
    }
});
Route::when('admin/advanced*', 'owner_role');
```

There are a few possibilities and it's up to you and your coding style where and how you want to check the roles and permissions.

**Comment by kadnan** [comment]
Perfect
