### ISSUE TITLE
Get role's permissions

### ISSUE THREAD

**Issue by doncadavona** [Zizaco/entrust#378]
In Eloquent, is there a way to set proper relations to the roles, permissions and role_permissions table to get a role's permissions? Or I hope Entrust already has a way for this.

Example:

// get role
$role = Role::where('name', 'admin');
// get the role's permissions
$rolePermissions = $role->permissions;

**Comment by jamiehd** [comment]
Try $role->perms

**Comment by doncadavona** [comment]
That worked! Why is it not named $role->permissions? I think it's better than "perm" for better meaning.
