### ISSUE TITLE
 Class 'Zizaco\Entrust\EntrustServiceProvider' not found in ProviderRepository.php : Laravel 5.1

### ISSUE THREAD

**Issue by shraddhabanerjee** [Zizaco/entrust#382]
Hi,

I am installing the entrust module using the link : https://github.com/Zizaco/entrust
Have made the installation section successfully. But when I run the command php artisan vendor:publish I get the following error.
I am new to laravel, cant figure out what is happening.

Please help.
Thanks in advance :)

shraddha@jai-B85M-D3H:/var/www/vurtax$ php artisan vendor:publish
PHP Fatal error:  Class 'Zizaco\Entrust\EntrustServiceProvider' not found in /var/www/vurtax/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146

[Symfony\Component\Debug\Exception\FatalErrorException]  
Class 'Zizaco\Entrust\EntrustServiceProvider' not found

**Comment by shraddhabanerjee** [comment]
Solved

**Comment by lovezhao311** [comment]
hi!
sorry , I really want to help you, but my English is not good . ^lol^

At 2015-09-23 20:19:40, "shraddhabanerjee" <notifications@github.com> wrote:


Hi,

I am installing the entrust module using the link : https://github.com/Zizaco/entrust
Have made the installation section successfully. But when I run the command php artisan vendor:publish I get the following error.
I am new to laravel, cant figure out what is happening.

Please help.
Thanks in advance :)

shraddha@jai-B85M-D3H:/var/www/vurtax$ php artisan vendor:publish
PHP Fatal error: Class 'Zizaco\Entrust\EntrustServiceProvider' not found in /var/www/vurtax/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146

[Symfony\Component\Debug\Exception\FatalErrorException]

Class 'Zizaco\Entrust\EntrustServiceProvider' not found

**Comment by miladganjali** [comment]
Hi, @shraddhabanerjee 
How you solved?

**Comment by cent040** [comment]
hi you can solve this after running this command 
`composer dump-autoload`

**Comment by miladganjali** [comment]
@cent040 Thank you!

**Comment by nikharjain5** [comment]
Thanks a lot....!!!!!@cent040

**Comment by sanduniYW** [comment]
Thank you very much...!!!@cent040

**Comment by caparra92** [comment]
Hello good day, I get this error
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'Zizaco\Entrust\EntrustServiceProvider' not found

My problem is that I installed my laravel project on a shared server and I do not have access to the console to run composer dump-autoload.
What can I do in this case to recognize the class? @cent040
Thank you
laravel version 5.5

**Comment by arfanmukhtar** [comment]
@caparra92  

make this route and run it.  
Route::get('/updateapp', function()
{
    \Artisan::call('dump-autoload');
    echo 'dump-autoload complete';
});
OR 
Simply run it on local and upload all files to server again. 
Thanks
