### ISSUE TITLE
Update Readme doc

### ISSUE THREAD

**Issue by oceanwap** [Zizaco/entrust#393]
"zizaco/entrust": "dev-laravel-5" doesn't has Middleware in source code.

**Comment by uax** [comment]
yes, when i use middleware in laravel 5.1.11, throw error:**Class Zizaco\Entrust\Middleware\EntrustRole does not exist**.
i already add:
    'role' => 'Zizaco\Entrust\Middleware\EntrustRole',
    'permission' => 'Zizaco\Entrust\Middleware\EntrustPermission',
    'ability' => 'Zizaco\Entrust\Middleware\EntrustAbility',
to routeMiddleware array in app/Http/Kernel.php,

some code in route.php:
Route::group(['prefix' => 'dashboard', 'namespace' => 'Dashboard', **'middleware' => ['role:admin']]**, function()
{
    Route::get('/', 'IndexController@index');
});
