### ISSUE TITLE
Master completely broken!

### ISSUE THREAD

**Issue by oldskool73** [Zizaco/entrust#396]
This commit has broken master :

https://github.com/Zizaco/entrust/commit/29c1930764166df95e760c7b597e5572b4b19aa9

The issue is that the 'tests/Middleware/MiddlewareTest.php' has been added to the autoloads in composer.json, but the tests dir isn't included in the source zip, so composer craps out when trying to generate the autoload.

As per my comment on the commit, I'm not sure why you'd want to always load the test middleware when using this package as an end user? I shouldn't be forced to have packages test stuff autoloaded into my production app. I'd suggest this whole commit should be reversed and you go back to loading the middleware as required when testing.

For now, the only solution is to install from source to get the tests dir included:

```
rm -rf vendor/zizaco/entrust
composer install --prefer-source
```

...although this obviously isn't ideal.

Related Refs : #391

**Comment by vpratfr** [comment]
+1 here! I would love to user middlewares and they are not available in the laravel-5 branch :/

**Comment by tuwannu** [comment]
Meanwhile waiting for PR #397 to be merged. Here's a workaround by adding "repositories" and changing zizaco/entrust to use `dev-middlewaretest-fix` in `composer.json` file.

    {
        ...
        "repositories": [
            {
                "url": "https://github.com/tuwannu/entrust.git",
                "type": "git"
            }
        ],
        "require": {
            ...
            "zizaco/entrust": "dev-middlewaretest-fix",
            ...
        },
        ...
    }

**Comment by micheleangioni** [comment]
Yeah, please @andrewelkins merge PR #397 .
Another workaround seems to use --prefer-source instead of --prefer-dist

**Comment by tuwannu** [comment]
#397 is merged. This issue can be closed.
