### ISSUE TITLE
Check Entrust 'isDeferred' method does not exist

### ISSUE THREAD

**Issue by psybox** [Zizaco/entrust#398]
I am trying to install Entrust but I'm receiving this error:

xx@yy:/var/www/html/my_app$php artisan vendor:publish
local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Zizaco\Entrust\EntrustFacade::isDeferred()' in /var/www/html/fretesja/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:119

**Comment by psybox** [comment]
Just need to put 'Entrust' => 'Zizaco\Entrust\EntrustFacade' in the config/app.php aliases.

**Comment by Mahmoudz** [comment]
probably all these non existing methods are caused because you are lassing collections instead of models to the entrust functions. Example:

```php
        $adminRole = Role::where('name', 'admin')->get(); // THIS WILL NOT WORK

        $adminRole = Role::where('name', 'admin')->first(); // THIS WORKS

        $user->attachRole($adminRole);
```
