### ISSUE TITLE
problem with EntrustUserTrait

### ISSUE THREAD

**Issue by saeedvaziry** [Zizaco/entrust#401]
Hi all.
i have this error :

FatalErrorException in User.php line 41:
Trait method can has not been applied, because there are collisions with other trait methods on App\Models\User

and this is my User.php file in laravel 5 :
<?php

namespace App\Models;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Model implements AuthenticatableContract,AuthorizableContract,CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;
    use EntrustUserTrait;

```
/**
 * The database table used by the model.
 *
 * @var string
 */
protected $table = 'users';

/**
 * The attributes that are mass assignable.
 *
 * @var array
 */
protected $fillable = ['name', 'email', 'password'];

/**
 * The attributes excluded from the model's JSON form.
 *
 * @var array
 */
protected $hidden = ['password', 'remember_token'];
```

}

**Comment by tuwannu** [comment]
Laravel 5 has its own [Authorization](http://laravel.com/docs/5.1/authorization) service out of the box. 

You just need to remove Authorizable trait by changing:

    use Authenticatable, Authorizable, CanResetPassword;

to

    use Authenticatable, CanResetPassword;

**Comment by 543310** [comment]
it worked!
thank you so much ;-)

**Comment by 543310** [comment]
@tuwannu one more question
i added following codes inside User class :

```
public function roles();
public function ability($roles, $permissions, $options);
public function can($permission);
public function hasRole($name);
```
but i received this error :
```
Non-abstract method App\Models\User::roles() must contain body
```

**Comment by tuwannu** [comment]
Why would you add those 4 lines of code? Those 4 methods are provided by `EntrustUserTrait`, and thus you don't need to implement them in your `User` class.

**Comment by 543310** [comment]
i thought that i have to enter manually.
thanks again.

**Comment by r4faelferreir4** [comment]
@tuwannu thanks help me

**Comment by AlexRadch** [comment]
You should remove EntrustUserTrait conflict with Laravel Authorizable trait!

For example, I use Laravel build in authorization to enable edit post that user created:
```php
$gate->define('update-post', function ($user, $post) {
    return $user->id === $post->user_id;
});

if ($user->can('update-post', $post))
```

**Comment by prog-24** [comment]
@AlexRadch great answer, been looking for this for weeks

**Comment by prog-24** [comment]
I think this issue should be closed or a proposal be made to change the name of the function
