### ISSUE TITLE
I GIVE UP

### ISSUE THREAD

**Issue by rickyspires** [Zizaco/entrust#414]
I give up.

I have been trying to get entrust to work for a week now with no luck.

The documentation is rubbish and it doesnt help that laravel changes every 5 mins. 

So unless someone has a fully working example of how this jigsaw goes together . it bye bye.

:(

**Comment by andrewelkins** [comment]
This isn't constructive.

**Comment by rickyspires** [comment]
hello. sorry. i was upset that i keep trying and not getting anywhere. i apologize !!!
