### ISSUE TITLE
Blade directives not working!

### ISSUE THREAD

**Issue by harishtoshniwal** [Zizaco/entrust#418]
All the 3 blade directives are not working on my blade views in the laravel app. Rather they show up as plain text.
Example below:

@role('admin')
<p>Something here</p>
@endrole

outputs this on my view in the browser:
@role('admin') Something here @endrole

**Comment by tomhoad** [comment]
+1

**Comment by harishtoshniwal** [comment]
@tomhoad We managed to solve the problem so sharing the solution with you.

- The current branch which is mentioned for installation in the docs does not contain the logic for the blade directives.
- We have found the the logic for the blade directives in the main master branch.
- So simply replace your file in the Vendors/Zizaco/entrust/src/Entrust/EntrustServiceProvider.php  with the file below:
https://github.com/Zizaco/entrust/blob/master/src/Entrust/EntrustServiceProvider.php

**Comment by shanka12** [comment]
I am also facing this issue. I tried @harishtoshniwal solution. but, no luck.
anyone got solutions?

**Comment by shanka12** [comment]
@harishtoshniwal  when I use your solution, getting following error.

FatalErrorException in Facade.php line 213:
Call to undefined method Illuminate\View\Compilers\BladeCompiler::directive()

**Comment by harishtoshniwal** [comment]
@shanka12 what version of laravel are you using?

**Comment by shanka12** [comment]
@harishtoshniwal  laravel 5

**Comment by harishtoshniwal** [comment]
@shanka12 be more specific with the laravel version number please.

**Comment by shanka12** [comment]
@harishtoshniwal  laravel 5.0.

**Comment by thomasbandit** [comment]
I also have this issue, using Laravel 5.1 and Entrust dev-laravel-5

**Comment by shanka12** [comment]
@tomhoad how to use ability method on view file?

**Comment by Khaled-AlSaeed** [comment]
+1

**Comment by AlexRadch** [comment]
Change documentation and remove blade directives!

**Comment by BojanKogoj** [comment]
I'm having this issue as well.

**Comment by michini** [comment]
si funciona...!! tenemos q copiar todo el contenido de el ServiceProvider.php del Repositorio a nuestro ServiceProvider.php de nuestra proyecto

**Comment by mortezarajabi** [comment]
I've this issue with laravel 5.1

**Comment by SirLamer** [comment]
Just to add to this, I would advise against editing the script files in the vendor package, since they will be overwritten during future package updates, if any. Also, any package distributions of your own work won't include your changes to the Entrust code. Instead, extend the EntrustServiceProvider in your own workspace and then direct the provider reference in app.cfg to that.

App\Providers\EntrustCustomServiceProvider.php:
```php
namespace App\Providers;

class EntrustCustomServiceProvider extends \Zizaco\Entrust\EntrustServiceProvider
{
    /**
     * Bootstrap the application services.
     *
     * @return void
     */
    public function boot()
    {
        parent::boot();

        // Register blade directives
        $this->bladeDirectives();
    }

    /**
     * Register the application services.
     *
     * @return void
     */
    public function register()
    {
        parent::register();
    }

    /**
     * Register the blade directives
     *
     * @return void
     */
    private function bladeDirectives()
    {
        // Call to Entrust::hasRole
        \Blade::directive('role', function($expression) {
            return "<?php if (\\Entrust::hasRole{$expression}) : ?>";
        });
        \Blade::directive('endrole', function($expression) {
            return "<?php endif; // Entrust::hasRole ?>";
        });
        // Call to Entrust::can
        \Blade::directive('permission', function($expression) {
            return "<?php if (\\Entrust::can{$expression}) : ?>";
        });
        \Blade::directive('endpermission', function($expression) {
            return "<?php endif; // Entrust::can ?>";
        });
        // Call to Entrust::ability
        \Blade::directive('ability', function($expression) {
            return "<?php if (\\Entrust::ability{$expression}) : ?>";
        });
        \Blade::directive('endability', function($expression) {
            return "<?php endif; // Entrust::ability ?>";
        });
    }
}
```

In config\app.php, change your service provider reference:
```php
'providers' => [
...
\App\Providers\EntrustCustomServiceProvider::class,
...
],
```

Also, while you're in config/app.php, don't forget there is a typo in the readme regarding the Entrust facade, so make sure the Face is set as so:
```php
'aliases' => [
...
'Entrust' => \Zizaco\Entrust\EntrustFacade::class,
...
],
```

**Comment by sunscreem** [comment]
@SirLamer Thank you for this - blade directives working a treat now in 5.2

**Comment by SirLamer** [comment]
I tried using the 5.2 branch but received many errors about comments in the code not being allowed. I understand the MySQL database driver does not allow code comments in the portions of code it handles - or something like that, don't quote me on the specifics. So I have to assume someone is developing and testing with a filesystem driver for data storage thus this wasn't caught. I chose to just stick to 5.1 in the meantime.

I am looking forward to the 5.2 branch as well, as I understand it also adds data caching so that the database doesn't get hammered with the same query again and again to check for roles - fine for me right now when I am developing myself, but would be bad for production.

**Comment by mseymour** [comment]
Try using `"zizaco/entrust": "^1.5"` instead of `"zizaco/entrust": "dev-laravel-5"`, which has the blade directives.

**Comment by diegofalciola** [comment]
@mseymour I tried what you said but it still doesn't work. Has it worked for anybody else?

**Comment by ariefadjie** [comment]
@harishtoshniwal Great ;) your solution is work (laravel 5.1.31) 

1. So simply replace your file in the Vendors/Zizaco/entrust/src/Entrust/EntrustServiceProvider.php with the file below: [https://github.com/Zizaco/entrust/blob/master/src/Entrust/EntrustServiceProvider.php](https://github.com/Zizaco/entrust/blob/master/src/Entrust/EntrustServiceProvider.php) 
2. After that you can do php artisan view:clear 
3. Then you can see error Call to undefined method Zizaco\Entrust\Entrust::ability()
4. That easy to solved Entrust::ability error you can replace file Vendors/Zizaco/entrust/src/Entrust/Entrust.php with [https://raw.githubusercontent.com/Zizaco/entrust/master/src/Entrust/Entrust.php](https://raw.githubusercontent.com/Zizaco/entrust/master/src/Entrust/Entrust.php)

**Comment by mortezarajabi** [comment]
I preferred to use [DynamicCodeNinja/RBAC](https://github.com/DynamicCodeNinja/RBAC). It works fine. It also supports inheritance.

**Comment by ubeyou** [comment]
`Call to undefined method Illuminate\View\Compilers\BladeCompiler::directive()`

I'm using laravel 5.0 and now I'm facing the above issue. I have to comment $this->bladeDirectives(); in order to make it work.

**Comment by sid606** [comment]
Have the same issue this helped me:
Downgrading to:
"zizaco/entrust": "1.4.1"

From this link:
https://github.com/Zizaco/entrust/issues/526
Hope this helps

**Comment by juetion** [comment]
I Have a solution .
modify file : 
App\Providers\EntrustCustomServiceProvider.php:
`
   /**
     * Register the blade directives
     *
     * @return void
     */
    private function bladeDirectives()
    {
        // Call to Entrust::hasRole
        \Blade::directive('role', function($expression) {
            return "<?php if (Auth::user()->hasRole{$expression}) : ?>";
        });

        \Blade::directive('endrole', function($expression) {
            return "<?php endif; // Entrust::hasRole ?>";
        });

        // Call to Entrust::can
        \Blade::directive('permission', function($expression) {
            return "<?php if (Auth::user()->can{$expression}) : ?>";
        });

        \Blade::directive('endpermission', function($expression) {
            return "<?php endif; // Entrust::can ?>";
        });

        // Call to Entrust::ability
        \Blade::directive('ability', function($expression) {
            return "<?php if (Auth::user()->ability{$expression}) : ?>";
        });

        \Blade::directive('endability', function($expression) {
            return "<?php endif; // Entrust::ability ?>";
        });
    }

`
and then 
php artisan view:clear
It can work now.

**Comment by harishtoshniwal** [comment]
@ubeyou  @sid606 here is the solution :)


https://github.com/Zizaco/entrust/issues/418#issuecomment-158879314

**Comment by SirLamer** [comment]
Do not edit vendor packages directly after download, that is bad show. If you really want to do that, fork the package and edit it in your copy, then include your version with Composer. Easier way is just to extend models in the vendor package to you own local project model and then overwrite whatever methods you want to in there.

**Comment by groundbreaker08** [comment]
@SirLamer very accurate. thanks. i missed out the app provider Facade .

**Comment by manishnakar** [comment]
oh god...

I found that there was typo for my facade in config/app.php

It was 
'Entrust' => Zizaco\Entrust\EntrustServiceProvider::class,

I chagned to 

'Entrust' => \Zizaco\Entrust\EntrustFacade::class,

and it worked for me..

Happy coding

**Comment by paishin** [comment]
you should update the documentation as well, it is still showing the older method
