### ISSUE TITLE
can and hasRole always return false

### ISSUE THREAD

**Issue by 06chaynes** [Zizaco/entrust#437]
I have created my permissions and role, attached the permissions to the new role, then attached the role to the user. That process is working properly and when I check the database all looks to be correct. 

When I load my user (Using: $user = User::where('id', '=', $userID)->first(); verified this is pulling the correct user) and check either the permission or role using one of these methods:
1) $isAllowed = $user->hasRole('global_admin');
2) $isAllowed = $user->can('view-organization');

$isAllowed always returns false regardless of the fact that the user does have the proper role and permissions assigned. 

Here is the top of my User model:

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Zizaco\Entrust\Traits\EntrustUserTrait;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, CanResetPassword, EntrustUserTrait;

Using Laravel 5.1

**Comment by 06chaynes** [comment]
I found this was due to the fact that I had changed the primary key of the users table to a different value other than the 'id' field. 

Is there a way around this so I can keep my custom primary key on the table?

**Comment by poppabear8883** [comment]
is it possible that you can do it here: https://github.com/Zizaco/entrust/blob/master/src/config/config.php

**Comment by 06chaynes** [comment]
Perfect, thank you.
