### ISSUE TITLE
`EntrustUserTrait` now requires a cache which allows for tags

### ISSUE THREAD

**Issue by imnotjames** [Zizaco/entrust#439]
There's no documentation for the change, but the EntrustUserTrait no longer works without a caching mechanism set up that supports tags.

Attempting to use Entrust without this causes a fatal error 

```
call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Cache\FileStore' does not have a method 'tags'
```

**Comment by imnotjames** [comment]
oops, already has an issue open, closing

**Comment by jidesakin** [comment]
@imnotjames Please, kindly provide the link to the opened issue. I'm having this issue too.

**Comment by imnotjames** [comment]
#422

**Comment by jidesakin** [comment]
Thanks @imnotjames
