### ISSUE TITLE
php artisan vendor:publish gives PHP fatal error

### ISSUE THREAD

**Issue by shinokada** [Zizaco/entrust#463]
On Laravel 5.2.5, when I run `php artisan vendor:publish` I get the following error.

    ➜  laravel-entrust  php artisan vendor:publish
    PHP Fatal error:  Call to undefined method Illuminate\Foundation\Application::bindShared() in    /Users/myname/Code/laravel-entrust/vendor/zizaco/entrust/src/Entrust/EntrustServiceProvider.php on line 72

    [Symfony\Component\Debug\Exception\FatalErrorException]
    Call to undefined method Illuminate\Foundation\Application::bindShared()

**Comment by santigarcor** [comment]
That problem can be solved with this https://github.com/Zizaco/entrust/issues/457

**Comment by shinokada** [comment]
It seems I have to run it in the homestead.

    homestead up
    cd Code/laravel-entrust
    php artisan vendor:publish

Then it created config/entrust.php.

**Comment by yourlocalwebmaster** [comment]
was able to fix this: in  EntrustServiceProviders.php change `$this->app->bindShared` to `$this->app->singleton`
https://laracasts.com/discuss/channels/laravel/l514-entrust-set-up-help

**Comment by viniciusgava** [comment]
Hello, I get this problem today, I see that we have a solution, but anyone knows why this fix is not done yet?
