### ISSUE TITLE
Caching (and Tagging) should be configurable

### ISSUE THREAD

**Issue by superdummy** [Zizaco/entrust#470]
Its great that Entrust has become a Caching Functionality, but the current implementation breaks a  lot of applications. 

https://github.com/Zizaco/entrust/commit/12c4eb09a376db64e6ebc5d08520050bc589a542

The Laravel Cache Drivers do NOT all support Tagging. And if a Cache Driver does not Support Tagging it kills the app. For example the very important and widely used Disk Cache Driver or Database Cache Driver do both not support Tagging. So in effect a lot of application simply stop working.

Please make this configurable via a config option  and/or do not use cache tags...

UPDATE:
It seems currently only the roles are cached? So in a lot of apps it is a must to also implement some permission caches on one own! To be the must usefull, versatile, generic Package, it would be best to simply make role Caching configurable(deault is on, but can be disabled via config option). Otherwise you will hit the next problem, that when being forced to implement your own Caching layer (due to the permissions caching requirments) you run into "double Caching" issues. 
And Of course: The best implementation would be Caching of Roles and Permissins and not using Tags. 

Thanks!

**Comment by imnotjames** [comment]
you can omit the caching by making your own implementation that matches the interface

**Comment by superdummy** [comment]
Thanks for the answer: Of course I can rewrite/patch and do a lot of things. But an application should be implemented wisely in the default config/functionality. 

And most of the applications out there in the wild will use these two cache drivers... Making this configurable should be very easy (and the furhter question is, if cache Tags are really needed at all).

**Comment by imnotjames** [comment]
Well, I meant in particular the traits which seem to have caching by default.

However, tag removal is in #422 which may help this to some extent

**Comment by superdummy** [comment]
@imnotjames Thanks! I have overlooked the https://github.com/Zizaco/entrust/issues/422. If this will be implemented, than everything is fine. 

Full Disabling of Caching would be fine to make this package even more usefull and versatile, but it is not a must for me, if Caching works with non Taggable Cache Drivers.
