### ISSUE TITLE
EntrustRoleTrait using old configuration not working on L5.2

### ISSUE THREAD

**Issue by nestormata** [Zizaco/entrust#476]
Hi,

I had the issue present when I was trying to regenerate the model information using ide-helper.
But indeed I noticed the trait is using an old location of the configuration that changed on Laravel 5.2.

The offending line is this one:
https://github.com/Zizaco/entrust/blob/master/src/Entrust/Traits/EntrustRoleTrait.php#L48

When is using `Config::get('auth.model')` when it should be using `Config::get('auth.providers.users.model')` 
According to the Laravel Upgrade guide https://laravel.com/docs/5.2/upgrade#upgrade-5.2.0 under Authentication -> Configuration file.

**Comment by JustSteveKing** [comment]
I was pointed to a fix: http://stackoverflow.com/questions/34529621/how-to-fix-in-laravel-5-2-zizaco-entrustmigration-class-name-validation

**Comment by nestormata** [comment]
Thanks, although my intention was to promote the fix into entrust code so that it get fixed correctly on next version for everyone.
There should be no use of configurations options that were removed from Laravel.
But thanks, hopefully the pull requests gets integrated and the fix be added to the next version for everyone.
