### ISSUE TITLE
Blank page after saving in laravel 5.2

### ISSUE THREAD

**Issue by ahmadalshugairi25** [Zizaco/entrust#484]
i have blank page after saving user data, the data already saved or updated but give me blank page 

this was the user model

/*******************************************************************/
use Illuminate\Foundation\Auth\User as Authenticatable;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Authenticatable
{
    use EntrustUserTrait;
   ........

}
/*******************************************************************/

i think that there was collision between user mode and (use EntrustUserTrait)
so what can i do to solve it.
thanks in advance

**Comment by akramwahid** [comment]
Did you check your laravel Log, if not please post the error message , 
and note that there is no an official release yet for a verision that support laravel 5.2,
You have to tweak the code adjust it to work laravel 5. if you can show me the error, i can help you to tweak it.. 

I have already working verision with Laravel 5.2 for entrust

**Comment by marcoraddatz** [comment]
I can confirm this error.

EntrustUserTrait::save() returns null, while the original Eloquent::save() return true.
