### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by MehmetNuri** [Zizaco/entrust#491]
Call to undefined method Illuminate\Foundation\Application::bindShared()

**Comment by HeroSony** [comment]
goto Zizaco\Entrust\EntrustServiceProvider then rename the bindShared() to singleton().

**Comment by tabirkeland** [comment]
Also seeing the the message:

`Call to undefined method Illuminate\Foundation\Application::bindShared()`

**Comment by freel132** [comment]
here is solution

https://github.com/Zizaco/entrust/issues/496

**Comment by MehmetNuri** [comment]
> 
> 
> here is solution
> 
> #496
