### ISSUE TITLE
Class 'EntrustSetupTables' not found with Laravel 5.2

### ISSUE THREAD

**Issue by psbhanu** [Zizaco/entrust#501]
`php artisan migrate:refresh --seed`
result with 

>   [Symfony\Component\Debug\Exception\FatalErrorException]
>   Class 'EntrustSetupTables' not found

My composer.json require object is:
```
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "doctrine/dbal": "^2.5",
        "laravelcollective/html": "^5.2",
        "zizaco/entrust": "^1.5"
    },
```

**Comment by psbhanu** [comment]
Running `composer dump-autoload` has resolve the issue.

**Comment by hugoooo** [comment]
thank you , psbhanu
