### ISSUE TITLE
SQL Migration error

### ISSUE THREAD

**Issue by Mohammed2050** [Zizaco/entrust#530]
After Migration 

 [Illuminate\Database\QueryException]                                         
  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL  
  : alter table `role_user` add constraint role_user_user_id_foreign foreign   
  key (`user_id`) references `` (`id`) on delete cascade on update cascade)    
                                                                               

                                                                          
  [PDOException]                                                          
  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint

**Comment by unioncast** [comment]
The same problem:

$ php artisan migrate

←[37;41m
       ←[39;49m
←[37;41m  [Illuminate\Database\QueryException]
       ←[39;49m
←[37;41m  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect tabl
e nam  ←[39;49m
←[37;41m  e '' (SQL: alter table `role_user` add constraint role_user_user_id_fo
reign  ←[39;49m
←[37;41m   foreign key (`user_id`) references `` (`id`) on delete cascade on upd
ate c  ←[39;49m
←[37;41m  ascade)
       ←[39;49m
←[37;41m
       ←[39;49m

←[37;41m
       ←[39;49m
←[37;41m  [PDOException]
       ←[39;49m
←[37;41m  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect tabl
e nam  ←[39;49m
←[37;41m  e ''
       ←[39;49m
←[37;41m
       ←[39;49m

**Comment by FayazK** [comment]
I faced the same problem. Please enter 
users
table name in Entrust migration file.
This will solve the issue

**Comment by Mohammed2050** [comment]
FayazK Thanks for your help,
Can you add steps here with code i`m beginer

**Comment by unioncast** [comment]
FayazK, sorry, what do you means ?

**Comment by obayesshelton** [comment]
You need to add your user table name, so for example change the following

`$table->foreign('user_id')->references('id')->on('')
`
to 

`$table->foreign('user_id')->references('id')->on('users')`

**Comment by haakym** [comment]
Same issue here, perhaps this could be added to the readme?

**Comment by obayesshelton** [comment]
@haakym my previous message will / should fix your issue.

**Comment by Mohammed2050** [comment]
obayesshelton, Thanks solved with adding user tables

**Comment by haakym** [comment]
@obayesshelton My bad, I actually worked it out myself before posting the same way you suggested. Was just posting to mention it should be in the docs. Thanks!

**Comment by HelaSk** [comment]
I have the same error also the permission and permission_roe tables don't show up on my database

**Comment by serak** [comment]
Ya this should be in the documentation . new to laravel users get to get lost in this kind of simple errors.
Thanks anyways

**Comment by eyosidesta** [comment]
$table->integer('user_id')->unsigned();
 $table->foreign('user_id')->references('id')->on('users')
        ->onUpdate('cascade')->onDelete('cascade');
=> this is my column for role_user table, but when I run php artisan migrate the following error arrives

SQLSTATE[HY000]: General error: 3780 Referencing column 'user_id' and referenced column 'id' in foreign key constraint 'role_user_user_id_foreign' are incompatible. (SQL: alter table `role_user` add constraint `role_user_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade on update cascade)

**Comment by eyosidesta** [comment]
I found the solution for the above problem I have posted... The solution is:
"bigInteger('user_id')" instead of "integer('user_id')" since my laravel version is 5.8
