### ISSUE TITLE
Group and Permissions

### ISSUE THREAD

**Issue by Minotti** [Zizaco/entrust#534]
Good evening, I would like to know if it is possible to revoke permission for a user who is in a role.

Example: 'admin' role has four permissions, 'p1', 'p2', 'p3', 'p4'.
John user is in the 'admin' role, but do not want him to have permission 'p1'.

What do I do?

**Comment by Cshion** [comment]
+1 , dont think this could be done because models dont support user-privilegies relation  (maybe im wrong please correct me) . A not nice solution could be create another role.
