### ISSUE TITLE
[BadMethodCallException] Call to undefined method Illuminate\Database\Query\Builder::attachPermission()

### ISSUE THREAD

**Issue by im4aLL** [Zizaco/entrust#536]
[BadMethodCallException] Call to undefined method Illuminate\Database\Query\Builder::attachPermission()

I tried to attach permission if not present and got error - 

``` php
<?php

use Illuminate\Database\Seeder;
use App\Role;
use App\Permission;
use App\User;

class AttachRolesAndPermissionsToUsers extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $admin = Role::where('name', 'admin')->first();
        $moderator = Role::where('name', 'moderator')->first();

        $createPost = Permission::where('name', 'create-post')->first();
        $editUser = Permission::where('name', 'edit-user')->first();


        // attach role
        $adminUser = User::where('email', 'a@gmail.com')->first();
        if(!$adminUser->hasRole('admin')) {
            $adminUser->attachRole($admin);
        }

        $moderatorUser = User::where('email', 'b@gmail.com')->first();
        if(!$moderatorUser->hasRole('moderator')) {
            $moderatorUser->attachRole($moderator);
        }

        // attach Permission
        if(!$adminUser->can(['create-post', 'edit-user'])) {
            $adminUser->attachPermissions([$createPost, $editUser]);
        }

        if(!$moderatorUser->can('create-post')) {
            $moderatorUser->attachPermission($createPost);
        }
    }
}
```

I take a look on EntrustUserTrait and method is not there. It's in EntrustRoleTrait. Do i need to use that as well with EntrustUserTrait? is that case there will be collision.

**Comment by im4aLL** [comment]
I just noticed that attachPermission should be attached to role to user. Is that right? I guess that's why it's not working.

**Comment by nikunjkansara** [comment]
I am facing the same issue, while configuring the package with Laravel 5.2. Is there any solutions?

**Comment by santigarcor** [comment]
the thing ist that the role is the one who has the permissions not the user, so you should attach permissions to a role

**Comment by Kristories** [comment]
@im4aLL user (`$adminUser`) can not attach permission, because it's not a role. 

```php
// attach Permission
if(!$adminUser->can(['create-post', 'edit-user'])) {
    $admin->attachPermissions([$createPost, $editUser]); // role attach permission
}
if(!$moderatorUser->can('create-post')) {
    $moderator->attachPermission($createPost); // role attach permission
}
```

**Comment by jonjie0317** [comment]
@im4aLL  have you solved your problem?  what was your solution?  I'm getting this error now. and Need help. thanks in advanced

**Comment by im4aLL** [comment]
@jonjie0317 yes, i was attaching permission to user. I had to attach permission to the role instead of user.

**Comment by jonjie0317** [comment]
@im4aLL  hm I think thats what I did, but not working. Look at my code below

```
use App\Models\Role;
use App\Models\Permission;

$admin = Role::where('name', 'admin');
$createPermission = Permission::where('name', 'create-post');
$admin->attachPermission($createPermission);
dd('Success.');
```

Please need help..

**Comment by manzwebdesigns** [comment]
@jonjie0317 did you add the Entrust* traits in your Role and Permission classes?

**Comment by jonjie0317** [comment]
@manzwebdesigns  yes, I did. Please check my code below

**Role.php**
```
<?php
namespace App\Models;

use Zizaco\Entrust\EntrustRole;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class Role extends EntrustRole
{
	use EntrustUserTrait;
}
```

**Permission.php**
```
<?php
namespace App\Models;

use Zizaco\Entrust\EntrustPermission;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class Permission extends EntrustPermission
{
	use EntrustUserTrait;
}
```

**AuthController.php**
```
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Role;
use App\Models\Permission;
use App\Http\Controllers\Controller;

class AuthController extends Controller
{

    public function createPermission(){

         $admin = Role::where('name', 'admin');
         $createPermission = Permission::where('name', 'create-post');
         $admin->attachPermission($createPermission);
         dd('Success.');
   
    }

}
```

**Comment by manzwebdesigns** [comment]
@jonjie0317 try this to be sure it is failing on the attachPermission:
```
         $admin = Role::where('name', 'admin');
         $createPermission = Permission::where('name', 'create-post');
         dd ($admin@manzwebdesigns.com,  $createPermission);
```
OR better yet, use xdebug instead of dd ()

HTH, Bud

**Comment by jonjie0317** [comment]
@manzwebdesigns  Wow! it worked. I just checked the data first using `dd()` and changing my code from:
```
$admin = Role::where('name', 'admin');
$createPermission = Permission::where('name', 'create-post');
$admin->attachPermission($createPermission);
dd('Success.');
```

to this:

```
$admin = Role::where('name', 'admin')->first();
$createPermission = Permission::where('name', 'create-post')->first();
$admin->attachPermission($createPermission);
dd('Success.');
```

Thanks men :)

**Comment by manzwebdesigns** [comment]
@jonjie0317 No problem, glad to help!  I am surprised I didn't notice that! :1st_place_medal:

**Comment by jonjie0317** [comment]
@manzwebdesigns  Yah, hahaha but why is my data not clickable?  I think if you set the foreign key in database migration then it will be clickable. hmm, just wondering about it, but anyways, thanks again 👍

**Comment by manzwebdesigns** [comment]
@jonjie0317 No problem.  BTW, you probably should have started a new thread instead of adding on to a closed one.

HTH,
Bud

**Comment by dop3ch3f** [comment]
Please i had the same issue and what fixed mine was i had to ensure that i had erased my previously defined models that affected entrust. i.e (User,Roles,Permissions)

**Comment by im4aLL** [comment]
@dop3ch3f I was having an issue because I was attaching permission to a user instead of role.
