### ISSUE TITLE
User's permission

### ISSUE THREAD

**Issue by tomhaoye** [Zizaco/entrust#548]
sometimes, we are in the same role, but have different permissions.
so, can we attach permissions to users instead of roles with 'entrust'?

**Comment by pjmartorell** [comment]
Look at the generated tables: a User has a Role, A Role has multple Permissions. These are all the possible relations.

**Comment by tomhaoye** [comment]
@pjmartorell Yes, i know about that, but i think that it might be lacked of flexibility. However, thank you so much.

**Comment by pjmartorell** [comment]
@tomhaoye Yes, chaining scopes is a bit hacky, even more when actually the repository pattern tries to decouple from the ORM...
