### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by microdesign** [Zizaco/entrust#550]
is the documentation up to date because $user->hasRole(['role1', 'role2']) return preg_queote expect string array give.

Also, we be wonderful if @role() can get more than one role as parameters

**Comment by pjmartorell** [comment]
@microdesign I agree that there's a lack of documentation. Anyway, `@role` in Blade templates already accepts more than one role. You can pass them as an array and also set the requireAll boolean. Check this in `EntrustServiceProvider.php`:

```
        \Blade::directive('role', function($expression) {
            return "<?php if (\\Entrust::hasRole{$expression}) : ?>";
        });
````

And this in `EntrustUserTrait.php`:

````
    public function hasRole($name, $requireAll = false)
    {
        if (is_array($name)) {
            foreach ($name as $roleName) {
                $hasRole = $this->hasRole($roleName);
                if ($hasRole && !$requireAll) {
                    return true;
                } elseif (!$hasRole && $requireAll) {
                    return false;
                }
            }
...
``````
I hope it helps you.

**Comment by microdesign** [comment]
Yep, thanks for this answer.
I didn't have time to search that is why I come here and comment.

Regards
