### ISSUE TITLE
User permissions belongsTo Relation points to wrong column

### ISSUE THREAD

**Issue by artmin** [Zizaco/entrust#557]
If I want to get a users collection of permissions like so:
`$user = App\User::first()`
`$user->perms`

I get the following error:
`Illuminate\Database\QueryException with message 'SQLSTATE[HY000]: General error: 1 no such column: permission_role.entrust_role_id (SQL: select "permissions".*, "permission_role"."entrust_role_id" as "pivot_entrust_role_id", "permission_role"."permission_id" as "pivot_permission_id" from "permissions" inner join "permission_role" on "permissions"."id" = "permission_role"."permission_id" where "permission_role"."entrust_role_id" = 1)'`

The table **permission_role** only has column **role_id**!

I am using "dev-laravel-5"

**Comment by apaleja** [comment]
Entrust do not have direct relationship of `permission` with `user` model. If you'd like to get all permission of a user, you can do something like this: 

    $user =App\User::first();
    $role = $user->roles()->with('perms');

this is give all roles with permissions for user.
