### ISSUE TITLE
@role directive for multiple roles

### ISSUE THREAD

**Issue by ahmadbadpey** [Zizaco/entrust#562]
I want to use @role directive for multiple defined roles like this : 
```
	@role('developer,administrator')
	<li><a href="/admin/permission">Permissions</a></li>
	@endrole

```

But this does not work. is it possible ?

**Comment by shanka12** [comment]
use like this.

@if(Auth::user()->hasRole(['developer', 'admin']))
<li><a href="/admin/permission">Permissions</a></li>
@endif

**Comment by Morinohtar** [comment]
Use like this:

`@role(['developer', 'administrator'])
    <li><a href="/admin/permission">Permissions</a></li>
    @endrole`

The same applies to @permission
