### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::cachedPermissions()

### ISSUE THREAD

**Issue by shanka12** [Zizaco/entrust#566]
When I use ability method, i'm getting following error (laravel 5.2)

ErrorException in Builder.php line 2161:
Call to undefined method Illuminate\Database\Query\Builder::cachedPermissions()

**Comment by rameshpaudel** [comment]
I am getting the same error

BadMethodCallException in Builder.php line 2251:
Call to undefined method Illuminate\Database\Query\Builder::attachRolesToUser()

**Comment by shanka12** [comment]
@rameshpaudel  Did you find the solution?

**Comment by rameshpaudel** [comment]
@shanka12 Changing the .env CACHE_DRIVER=array solved my problem however, I think its not a permanent solution.

**Comment by praveensns** [comment]
add this line in composer.json 
"zizaco/entrust": "5.2.x-dev"

**Comment by shanka12** [comment]
@rameshpaudel I am already using array. still not work ability method.
@praveensns  I am using same version

**Comment by mupmzfqot** [comment]
Any solution ?
I am already using CACHE_DRIVER=array and "zizaco/entrust": "5.2.x-dev". But same.

**Comment by vrkansagara** [comment]
the same problem with my code also.

**Comment by vrkansagara** [comment]
Hello Guys I found the quick solution for this issue is do as bellow.

find the Role.php file and updated as bellow
`use Zizaco\Entrust\EntrustRole;`

and extend with `EntrustRole`
Hope it work for you also. :+1:

**Comment by wugang8068** [comment]
vrkansagara's answer worked for me!

**Comment by vrkansagara** [comment]
@wugang8068  :+1:

**Comment by LivingStonZhang** [comment]
use Zizaco\Entrust\EntrustRole;

and extend with EntrustRole 
This solution is useful for my product~I hope you guys can try~ @vrkansagara  Thank you

**Comment by epalen** [comment]
I have this same error in the version of Laravel 5.3 and I have tried the above indications and the error persists.

Does anyone have a solution in this case?

**Comment by epalen** [comment]
I find where I was generating my error, it was on the routes that defined them this way:

```
// For Role
	Route::get('roles',[
		'as'=>'roles.index',
		'uses'=>'RoleController@index',
		'middleware' => ['permission:role-list|role-create|role-edit|role-delete']
    ]);
```

**Comment by THEMBOCHARLES** [comment]
After changing CACHE_DRIVER=file to CACHE_DRIVER=array. Stop the artisan server and then restart it.

**Comment by THEMBOCHARLES** [comment]
But the best solution for me was.
1. set app/cache to 'default' => env('CACHE_DRIVER', 'redis'),
2.CACHE_DRIVER=redis in .env
3. In your composer.json add "predis/predis": "^1.1"
4. run composer update
5.restart your artisan server. 
6. It works

**Comment by AbhilashDesign** [comment]
I was getting the same error because of using "ability" to check the role and permissions. I used hasRole(['admin','moderator','user']) it is working fine. Hope this may help to someone.

**Comment by afrasiyabhaider** [comment]
Same error

**Comment by vrkansagara** [comment]
@afrasiyabhaider I moved to another package so cant able to help
