### ISSUE TITLE
php artisan migrate:Syntax error or access violation: 1103 Incorrect table name

### ISSUE THREAD

**Issue by zwl1619** [Zizaco/entrust#567]
I am using "zizaco/entrust": "5.2.x-dev", what does this mean?
```
$ php artisan migrate
Migration table created successfully.

  [Illuminate\Database\QueryException]

  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: alter table `r
ole_user` add constraint role_user_user_id_foreign foreign key (`user_id`) references `` (`id`) on delete
 cascade on update cascade)

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''
```

**Comment by huangered** [comment]
please refer to https://github.com/Zizaco/entrust/issues/563#issuecomment-210244696
add user table name in migration script

**Comment by hihoZhou** [comment]
on your database/migrations/<timestamp>_entrust_setup_tables.php ,the code what create role_user table,change "$table->foreign('user_id')->references('id')->on('')
                ->onUpdate('cascade')->onDelete('cascade');"
to "$table->foreign('user_id')->references('id')->on('users')
                ->onUpdate('cascade')->onDelete('cascade');"
function on missing code 'users'

**Comment by shealan** [comment]
Thank you

**Comment by HelaSk** [comment]
I have the same error and i fixe it  but the permission and permission_role tables didn't show up on my database

**Comment by santigarcor** [comment]
you could check my fork i have solved a lot of issues and a friend of mine and i are maintaining it

**Comment by HelaSk** [comment]
Ok thanks

**Comment by HelaSk** [comment]
Can you guide me to find the solution

**Comment by santigarcor** [comment]
Just follow the instructions of the docs and you are done! :D

**Comment by iacordova** [comment]
Thanks it works for me, put "users' table
