### ISSUE TITLE
Entrust need more people to manage issue

### ISSUE THREAD

**Issue by devsalman** [Zizaco/entrust#568]
Hi @andrewelkins and @Zizaco, currently entrust have so many issue (183) and pull request (20) but they lack of response from the core developer. i think entrust have an oportunity to become big and more stable but as i see on your public activity this repository is not your priority for now. do you need some help?

**Comment by andrewelkins** [comment]
We'll take help, sure

**Comment by devsalman** [comment]
hi @andrewelkins, how can we help entrust if we never get feedback or response for our pull request? :)

**Comment by santigarcor** [comment]
That's true, you should add more active collaborators.

**Comment by andrewelkins** [comment]
Agreed. I currently don't have perms to do that. I've ask Zizaco for this, so I can take care of it.

**Comment by santigarcor** [comment]
@andrewelkins that's excellent

**Comment by moos3** [comment]
@andrewelkins and @Zizaco I would love to help with this project also.

**Comment by santigarcor** [comment]
@moos3 i made a fork of this package because this one isn't getting the right attetion, you can check ir out in my profile

**Comment by andrewelkins** [comment]
I'd love to add both of you to the project. Just need to get the permissions to do it.

**Comment by andrewelkins** [comment]
We're adding you all to the project!

**Comment by dodyagung** [comment]
but there are still 276 pending issues and 27 pending pull requests at this time cc @andrewelkins @santigarcor @moos3 @devsalman

**Comment by santigarcor** [comment]
@dodyagung I'm not working on entrust i have been working on my own `fork`, it's called laratrust.
