### ISSUE TITLE
BadMethodCallException - This cache store does not support tagging - hasRole in Controller

### ISSUE THREAD

**Issue by ejeanneaubc** [Zizaco/entrust#580]
#Hi All !

I have a problem, i want to use hasRole method in my Controller but i have this error : 

> BadMethodCallException in Repository.php line 367:
> This cache store does not support tagging.

My controller : 

```
namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Auth;
use App\User;

class SchoolsController extends Controller
{
    public function index()
    {
        $user = Auth::user();

        $role = $user->hasRole('superadmin');
        dd($role);

        return view('admin.schools.index', array(
            'title' => 'Schools', 
            'icon' => 'graduation-cap',
            'parent_title' => 'Contacts',
            'parent_icon' => 'accounts',
        ));
    }
}
```

Can you help me please ?

Thank's a lot !

**Comment by netpok** [comment]
Hi!

The current version of Entrust is not supporting the file cache driver, you should change it to something else.

**Comment by ejeanneaubc** [comment]
I found my problem... The file cache driver is not compatible with tags. I change it to "Array" and it's works. I hope this issue can help anyone .. !

**Comment by ejeanneaubc** [comment]
Thank's netpok, i write at the same moment ! It's ok, thank's a lot !

**Comment by jidesakin** [comment]
@netpok This works for me as well

**Comment by Shaimaa-Mohamed** [comment]
when i add new user,edit and delete. this exception appear 
**BadMethodCallException in Repository.php line 367: This cache store does not support tagging.**
but,  actually add,edit,delete when i go to the page of users ????
