### ISSUE TITLE
Laravel 5.2 issues with soft deletes

### ISSUE THREAD

**Issue by omer414** [Zizaco/entrust#588]
Just came across this issue on the latest version of laravel 5.2. As soon as you add the SoftDelete trait to the class, it  gives this error.

`Trait method restore has not been applied, because there are collisions with other trait methods on App\Http\Models\User`

Entrust is great, but i have been facing similar issues with softdeletes on earlier versions of laravel as well. Can anybody please fix this?

```
class User extends Authenticatable
{
    use EntrustUserTrait;
    use SoftDeletes;
```

**Comment by ChristianGiupponi** [comment]
I get the same error

**Comment by tobias-kuendig** [comment]
See https://github.com/Zizaco/entrust/issues/379#issuecomment-202785182

**Comment by andfelzapata** [comment]
Any luck ?

**Comment by omer414** [comment]
Yes, @tobias-kuendig 's solution worked for me.

**Comment by andfelzapata** [comment]
Yeah, I missed that comment, for some reason I read very comment but that one.

**Comment by santigarcor** [comment]
In my fork i have solved this issue you can try this [here](https://github.com/santigarcor/laratrust)

**Comment by cjmling** [comment]
Becareful though. 
https://github.com/Zizaco/entrust/issues/379#issuecomment-255693781
