### ISSUE TITLE
Using oauth and role/permission in middleware returns 403 Forbidden

### ISSUE THREAD

**Issue by emmanesguerra** [Zizaco/entrust#590]
Hi Guys, 

First of all, sorry for my English.

I'm trying to access a page with middleware (api.auth and role and permission)

`$api->version('v1', ['middleware' => 'api.auth'], function ($api) {`
`    $api->get('user/validate', 'App\Http\Controllers\UserController@index');`

    $api->group(['prefix' => 'test', 'middleware' => ['role:developers']], function($api) {
        $api->get('/manage2', 'App\Http\Controllers\UserController@index');
        $api->get('/manage', ['middleware' => ['permission:create-delivery'], 'uses' => 'App\Http\Controllers\UserController@index']);
    });
`});`

Accessing the first link **user/validate** works, it returns the expected return when the access_token pass was valid and it returns 401 when the access_token was not valid

but accessing **test/manage2** and **test/manage** always return 403 Forbidden.

I have debug the scripts and found out that in this class **\Zizaco\Entrust\Middleware\EntrustRole.php** returns the forbidden.

`if ($this->auth->guest() || !$request->user()->hasRole(explode('|', $roles))) {
abort(403)`

I have **var_dump()** each condition and it returns 

>$this->auth->guest()  = **TRUE**

>!$request->user()->hasRole(explode('|', $roles)) = **Call to a member function hasRole() on null**

Going deep to thesefunctions **(auth->guest() and user()->hasRole())**, it seems that the user is undefined, it seems that even though I have passed the access_token correctly the Class doesn't recognize the user.

Can anyone tell me what am I missing? I'm just following the youtube video of **Lets Code Easy**
**Restful API using Laravel** Dingo \ Zizaco \ LucaDegasperi

I wanted the roles and permission to work in Middleware, not in Controllers even tough i can always use the can() and hasRole() in checking whose user have access to this resources.

Thank you for your response.

**Comment by andersonagarcia** [comment]
+1

**Comment by emmanesguerra** [comment]
Hi Guys,

I have came up to a solution.

Below are the scripts that I have use in order to make the role and permission works in middleware

for **EntrustRole.php**, I change the script in the **handler** method to...

> $userId = Authorizer::getResourceOwnerId();
> 		$user = User::find($userId)->first();
> 		$ret = $user->hasRole(explode('|', $roles));
> 		if($ret)
> 		{
> 			return $next($request);
> 		}
> 		else
> 		{
> 			abort(403);
> 		}

and **use** the classes 

> use App\User;
>use LucaDegasperi\OAuth2Server\Facades\Authorizer;

for **EntrustPermission.php**, I change the script in the **handler** method to...

>$userId = Autho rizer::getResourceOwnerId();
> 		$user = User::find($userId)->first();
> 		$ret = $user->can(explode('|', $permissions));
> 		if($ret)
> 		{
> 			return $next($request);
> 		}
> 		else
> 		{
> 			abort(403);
> 		}

and **use** the classes 

> use App\User;
>use LucaDegasperi\OAuth2Server\Facades\Authorizer;

Applying these scripts make my middleware works.

I'm thinking. Overriding EntrustRole.php and EntrustPermission.php is not a good practice, but while waiting for a best and right solution to make this work I'll use these for now.

PS.
if you have a better solutions/suggestions, or my solution is not correct or not a good way to handle this. Please correct me. I'm open for suggestions.

**Comment by lvandyk** [comment]
I have the exact same issue, so what I did is create a DingoCompatibleTrustRole in my middleware folder and extended the class and added the above fix in the handle method. Then I just set `'role' => \App\Http\Middleware\DingoCompatibleEntrustRole::class` in the $routeMiddleware in Kernel.php

**Comment by z1z2** [comment]
Just add 'auth:api' before the entrust middleware can solve it. I tested in Laravel 5.3.
Like this:

`
Route::group(['middleware' => ['auth:api','permission:create-post']], function() {
 
   Route::get('/create', function(){

        return 'create';

    });

});
`

**Comment by z1z2** [comment]
@emmanesguerra 
Add 'auth:api' before the entrust middleware can solve the problem. Like this:
> Route::group(['middleware' => ['auth:api','permission:create-post']], function() {
>     Route::get('/create', function(){
>         return 'create';
>     });
> });
Tested under Laravel 5.3

**Comment by tcetin** [comment]
I am using JWT Authentication. And I faced same problem. I tried this and. It worked for me.

Basically Entrust doesnt find Authenticated user.So I changed EntrustRole Middleware Like this:

`		$user = \JWTAuth::parseToken()->authenticate();

		if (!is_array($roles)) {
			$roles = explode(self::DELIMITER, $roles);
		}

		if (!$user->hasRole($roles)) {
			abort(403);
		}

		return $next($request);`
