### ISSUE TITLE
Fluent trait methods

### ISSUE THREAD

**Issue by KKSzymanowski** [Zizaco/entrust#600]
Why not make `Trait` API fluent?

Eg. in `EntrustRoleTrait` the `attachPermissions` method could look like
```
    public function attachPermissions($permissions)
    {
        foreach ($permissions as $permission) {
            $this->attachPermission($permission);
        }

        return $this; // <---
    }
```

I haven't found any similar issues. Am I the only one that finds this useful:
`$role = Role::create($roleAttributes)->attachPermissions($permissions); `

Will you do it or should I make a PR? Are there any downsides to this approach?

**Comment by santigarcor** [comment]
If you want i have a fork of this code and with some features solved made the PR and i could take a look

**Comment by santigarcor** [comment]
@KKSzymanowski the fluent api is already implemented in my code

**Comment by KKSzymanowski** [comment]
Thank you very much. I will definitely take a look at your fork.
