### ISSUE TITLE
php artisan db:seed --class=RolesTableSeeder

### ISSUE THREAD

**Issue by chebonv** [Zizaco/entrust#604]
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 1 passed to Zizaco\Entrust\Middleware\EntrustRole::__construct() must be
  an instance of Illuminate\Contracts\Auth\Guard, none given, called in C:\xampp\htdocs\myAuth\d
  atabase\seeds\RolesTableSeeder.php on line 13

**Comment by chebonv** [comment]
i have finally got the solution

**Comment by Hofsep** [comment]
what is the solution?
