### ISSUE TITLE
Is it possible to attach roles for guest users?

### ISSUE THREAD

**Issue by Redigast13** [Zizaco/entrust#651]
I want to check permissions for guest users. Is it possible?

**Comment by rkgarcia** [comment]
what's the difference between guest users?

**Comment by Sarav-S** [comment]
@Redigast13 I don't think that's possible, But can you explain your scenario bit more? Like how would you like to check permission?

**Comment by Sarav-S** [comment]
#651

**Comment by Redigast13** [comment]
> @Redigast13 I don't think that's possible, But can you explain your scenario bit more? Like how would you like to check permission?
I would like to check permissions using authorization policies. LIke "$user->can('get-users');" in policy. I store permissions in DB using Zizaco\Entrust module.
But if user is not authenticated then the policy will not be executed.
I solved this problem using middleware, that login user as guest model if user is not authenticated.
```
public function handle($request, Closure $next)
    {
        if (!Auth::check()) {
            $guestUser = User::where('is_guest', 1)->first();

            if ($guestUser) {
                Auth::login($guestUser);
            }
        }

        return $next($request);
    }
```
