### ISSUE TITLE
Undefined class constant 'can'

### ISSUE THREAD

**Issue by madhusudhan1234** [Zizaco/entrust#653]
I got this type of error. Please help me to solve this.
![entrustundefinedcontant](https://cloud.githubusercontent.com/assets/8276878/18301265/cc3c311a-74ef-11e6-883f-e763d216573e.png)

**Comment by madhusudhan1234** [comment]
Now it is solved, The problem was due to 
@permission('item-create')
        <a class="btn btn-success" href="{{ route('itemCRUD2.create') }}"> Create New Item</a>
@endpermission

It solved in this way .

@permission(('item-create'))
        <a class="btn btn-success" href="{{ route('itemCRUD2.create') }}"> Create New Item</a>
@endpermission

**Comment by marijnhurkens** [comment]
Are you using Laravel 5.3? Same problem as #657?

**Comment by madhusudhan1234** [comment]
@marijnhurkens yes I was using Laravel 5.3 . Thank you for the reply

**Comment by cent040** [comment]
it's working fine with Laravelv5.3 i am using it.
