### ISSUE TITLE
Forgotten 'users' reference in database migration file

### ISSUE THREAD

**Issue by Xheno** [Zizaco/entrust#655]
Greetings, you sort of forgot to add the users table when mapping the constraint that references the user_id in the pivot table role_user, instead there is space for a string ('').
Thanks, Happy Debugging.

![git](https://cloud.githubusercontent.com/assets/4604697/18414585/742f68fc-77d8-11e6-9024-47173fff43ef.JPG)

**Comment by Sarav-S** [comment]
Hi Xheno, 

This is not an issue. Please refer #654
