### ISSUE TITLE
Argument 1 passed to Illuminate\Auth\EloquentUserProvider::validateCredentials() must be an instance of Illuminate\Contracts\Auth\Authenticatable, instance of App\User given, called in /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php on line 385 and defined

### ISSUE THREAD

**Issue by shea786** [Zizaco/entrust#671]
Hi,

Laravel 5.2

I am getting the following error while trying to login

Argument 1 passed to Illuminate\Auth\EloquentUserProvider::validateCredentials() must be an instance of Illuminate\Contracts\Auth\Authenticatable, instance of App\User given, called in /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php on line 385 and defined

Can someone help me please,

Thanks

**Comment by shea786** [comment]
If i change in the users model,

class User extends Eloquent 
to 
class User extends Authenticatable

**Comment by alihesari** [comment]
I also change in the users model then it works fine.

**Comment by ibnfarouk** [comment]
this is my User model and i still having this error :( 

```
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Authenticatable
{
    use EntrustUserTrait;
    use Notifiable;
```

**Comment by webexpert4rv** [comment]
jjhhhfghfh

> fghfghfh

- [ ] fghfggggggggggg

- [[`gfhfhfh`](fhfghfhf)](fghffffffffffffffffhfghf)

**Comment by HarshHash** [comment]
Hi

Laravel 5.4 and Using JWT AUTH

I am getting the following error while trying to login

(1/1)  ErrorException  Argument 1 passed to Illuminate\Auth\EloquentUserProvider::validateCredentials() must be an instance of Illuminate\Contracts\Auth\Authenticatable, instance of App\User given, called in vendor\laravel\framework\src\Illuminate\Auth\SessionGuard.php on line 380 and defined

Can someone help me please,

Thanks

**Comment by daskon** [comment]
@shea786  you are saying temporary solution. changing 

 class User extends Eloquent
to
class User extends Authenticatable

will be fine for the moment, but user model signup functionality need Eloquent model.

**Comment by jaypotato** [comment]
any solution?

**Comment by ghost** [comment]
The solution provided by @gieroj in [this issue](https://github.com/jenssegers/laravel-mongodb/issues/702) worked fine for me in Laravel 5.4

```php
use Illuminate\Contracts\Auth\Authenticatable;
use Illuminate\Auth\Authenticatable as AuthenticableTrait;

class User extends \Eloquent implements Authenticatable
{
    use AuthenticableTrait;
    // ...
```

**Comment by nellytadi** [comment]
Yup this worked fine for me, thank you!

**Comment by cjustinobi** [comment]
This is cool @piedimonte 

You deserve some accolades!

**Comment by philipafemikhe** [comment]
I was getting this error and I was able to fix it after noting a difference in my User model path
in App\config\auth file, I changed 
'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\Models\User::class,
            'table' => 'users',
        ],
    ],

and replaced with
'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],

that resolved the issue in my case

**Comment by huotsokhalion** [comment]
### vbn

**Comment by huotsokhalion** [comment]
love

**Comment by daiki0730** [comment]
ありがとう！

**Comment by daiki0730** [comment]
@piedimonte thanx

**Comment by hosseinfallahi75** [comment]
"message": "Argument 1 passed to Illuminate\\Auth\\EloquentUserProvider::validateCredentials() must be an instance of Illuminate\\Contracts\\Auth\\Authenticatable, instance of App\\Models\\CustomersVerify given, called in C:\\xampp\\htdocs\\asanbiamoz\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\SessionGuard.php on line 422",

**Comment by LucasBarbosa88** [comment]
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable

this worked for me

**Comment by sammybammy52** [comment]
> use Illuminate\Foundation\Auth\User as Authenticatable;
> 
> class User extends Authenticatable
> 
> this worked for me

Thanks, this worked for me

**Comment by daffaharizaleid** [comment]
> use Illuminate\Foundation\Auth\User as Authenticatable;
> 
> class User extends Authenticatable
> 
> this worked for me

Thanks, this worked for me
