### ISSUE TITLE
Error with migration in Laravel 5.1

### ISSUE THREAD

**Issue by blonder413** [Zizaco/entrust#675]
I try the migration but i have an error:

<code><pre>
[Symfony\Component\Debug\Exception\FatalThrowableError]
Class name must be a valid object or a string
</pre></code>
I don't know what to do

**Comment by Gonzalo2324** [comment]
Hello, you have to edit the file vendor/zizaco/entrust/src/commands/MigrationCommand.php on lines 84, 85, this resulting
     
        $usersTable  = Config::get('auth.table');
        $userModel   = Config::get('auth.model');

**Comment by Gonzalo2324** [comment]
after that execute the instruction:

php artisan entrust:migration

**Comment by blonder413** [comment]
thank you very much, it works now.

**Comment by rscotten** [comment]
@Zizaco Please fix this Config::get('auth.model') in EntrustRoleTrait

**Comment by jonjie0317** [comment]
Hey guys, Good day. Can you help me with [this issue](https://github.com/Zizaco/entrust/issues/775). Thanks!
