### ISSUE TITLE
When i use @role or @permission in blade laravel will throw ‘T_CONSTANT_ENCAPSED_STRING’...

### ISSUE THREAD

**Issue by ellisfan** [Zizaco/entrust#682]
Laravel Framework version 5.3.19

when i use `@role` or `@permission` in blade, laravel will throw `'T_CONSTANT_ENCAPSED_STRING'` for me.
I find an error in view cache

Blade Code:`@permission('Permission')`
View Code:`<?php if (\Entrust::can'Permission') : ?>`

it's lost a parenthese.

**Comment by foommiinn** [comment]
**First solution:**
Use in Blade template next
@role(('admin'))
    <h1>test</h1>
@endrole

**Second solution:**
Update the file [site/vendor/zizaco/entrust/src/Entrust/EntrustServiceProvider.php](https://github.com/Zizaco/entrust/pull/658/commits/976628d94048421f6006692edbefd4f49332801e#diff-fd67755a24979e24a74dd15b4c30d112)

**Comment by AhmadShahid** [comment]
I also faced same issue. when i looked into it then i find starting bracket is missing all three blade directives role,ability and permission in site/vendor/zizaco/entrust/src/Entrust/EntrustServiceProvider.php

**Comment by foommiinn** [comment]
View the [commit](https://github.com/marijnhurkens/entrust/blob/976628d94048421f6006692edbefd4f49332801e/src/Entrust/EntrustServiceProvider.php)  or use fork for  [Laravel 5.3](https://github.com/klaravel/ntrust)
