### ISSUE TITLE
role can't get users. 5.2.x-dev

### ISSUE THREAD

**Issue by foreverglory** [Zizaco/entrust#689]
Created a leader role, and add some users to this role `$user->attachRole($role)` 
However, when use of
```php
$role = Role::where('name', 'leader')->first();
$users = $role->users();
```
$users is empty.

in the Mysql, table `role_user` have data.

**Comment by tosslife** [comment]
same

**Comment by tosslife** [comment]
your Modles  Role.php

use Zizaco\Entrust\EntrustRole;

class Role extends EntrustRole

**Comment by huangered** [comment]
add    'model' =>"app\User", in config/auth.php

in entrustroletrait.php
/**
     * Many-to-Many relations with the user model.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function users()
    {
        return $this->belongsToMany(Config::get('auth.model'), Config::get('entrust.role_user_table'),Config::get('entrust.role_foreign_key'),Config::get('entrust.user_foreign_key'));
       // return $this->belongsToMany(Config::get('auth.model'), Config::get('entrust.role_user_table'));
    }

otherwise the config::ger('auth.model') is null
