### ISSUE TITLE
InvalidArgumentException in EntrustUserTrait.php line 176:

### ISSUE THREAD

**Issue by wimurk** [Zizaco/entrust#693]
Error by passing string to the middleware 'validate_all' option.
'middleware' => ['ability:owner,view-projects,true']]
The option true isn't passed as boolean. 
fixed it by adding this to the code

file : EntrustUserTrait
row: 163

```
//Convert to boolean if string is passes
if(isset($options['validate_all']) && !is_bool($options['validate_all'])){
      $options['validate_all'] = ($options['validate_all'] === 'true')?true:false;
}
```

**Comment by rogercrandall** [comment]
You can just leave the boolean argument off and it defaults to true.

**Comment by wimurk** [comment]
Yes, But thats not the problem. The code checks if the parameter is a boolean.

**Comment by luishype** [comment]
i fix the problem on 
file: Zizacon\Entrust\Middleware
row: 40

public function handle($request, Closure $next, $roles, $permissions, $validateAll = false)
	{
		if ($this->auth->guest() || !$request->user()->ability(explode('|', $roles), explode('|', $permissions), array('validate_all' => (bool)$validateAll))) {
			abort(403);
		}

		return $next($request);
	}
