### ISSUE TITLE
find all users that can('some_permisssion') and send notification

### ISSUE THREAD

**Issue by tuytoosh** [Zizaco/entrust#713]
Hi, I want to get all users that has some permission and send them a notification... how to get them?
Thanks

**Comment by tuytoosh** [comment]
Is not there anyone to me question?

**Comment by tianyong90** [comment]
```php
$user = \App\User::whereHas('roles', function ($roleQuery) {
    $roleQuery->whereHas('perms', function ($permissionQuery) {
        $permissionQuery->where('name', 'the_permissionname');  // or other condigions...
    });
})->get();
```
@tuytoosh Try like this.

**Comment by tuytoosh** [comment]
Thanks, but I changed my code to my own role_permission style without entrust :+1: 

Thanks again @tianyong90
