### ISSUE TITLE
return redirect()->back()

### ISSUE THREAD

**Issue by luizmagao** [Zizaco/entrust#714]
Então, estou com problemas Zizaco, uso atualmente o Defender, mas gostei muito do estilo do seu Project Entrust, porém não sei o que devo fazer para fazer um simples redirect()->back() quando o cidadão não estiver com a permissão.

Poderia me da uma luz?

**Comment by luizmagao** [comment]
Zizaco consegui aqui, 

public function handle($request, Closure $next, $roles)
	{
		if ($this->auth->guest() || !$request->user()->hasRole(explode('|', $roles))) {
			-> mudei aqui -> abort(403);
		}

		return $next($request);
	}

**Comment by luizmagao** [comment]
Como pode me ajudar?

**Comment by devsalman** [comment]
Hi @luizmagao, can you provide the explanation in English? it will help the others to understand your problem :)

**Comment by luizmagao** [comment]
I would like to use a redirect () and I do not know how to do it, in the case of ZIZACO I only know using the 403 error, but I really want to use a simple redirect back

**Comment by devsalman** [comment]
Hi @luizmagao, basically entrust will call `abort(403)` when user doesn't have permission to access the page. It will raise `HttpException` with the status code 403. So, you can use Laravel exception handler in `app\Exception\Handler.php` like this:

```
/**
* Render an exception into an HTTP response.
*
* @param  \Illuminate\Http\Request  $request
* @param  \Exception  $e
* @return \Illuminate\Http\Response
*/
public function render($request, Exception $e)
{
    if($e instanceof HttpException 
        && $e->getStatusCode() == 403) {

        return redirect()->route('home');
    }

    return parent::render($request, $e);
}
```

I've tried using `redirect()->back()` method but i always get `too many redirect` error in my browser (still don't know the reason) so i'm using `redirect()->route()` to redirect user when they are don't have permission to access the page.

**Comment by devsalman** [comment]
this issue is inactive, so i will close this issue.. if something happened again you can re-open the issue
