### ISSUE TITLE
why package still in development version ?

### ISSUE THREAD

**Issue by mohamed-akef** [Zizaco/entrust#717]
why no stable version from the package, I need to use it in large scale app and I'm afraid because of it still in the development version.
any help?

**Comment by DeeJaVu** [comment]
This package is dead, use the actively maintained fork from here https://github.com/santigarcor/laratrust

**Comment by Zizaco** [comment]
#840 was merged. I strongly believe that it should be fully 5.5 compatible by now. :smiley: 

Anyway I will be doing some cleanup and improvement on the package over the next weeks.
