### ISSUE TITLE
Laravel 5.3.29 compatibility

### ISSUE THREAD

**Issue by paligiannis** [Zizaco/entrust#723]
Is laravel 5.3.29 compatible with entrust. What have I to do in order to install it?

**Comment by ryanicle** [comment]
I just installed entrust with Laravel 5.3.29 last week. It is compatible till now. I have no issues so far.

**Comment by Archcry** [comment]
I've had Entrust running on my Laravel 5.3 installation for a short period of time and everything seems to work properly.
Though Laravel 5.4 has some breaking changes and is not easily compatible with Entrust you can still get it running there.
