### ISSUE TITLE
BadMethodCallException with message 'Call to undefined method Illuminate\Database\Query\Builder::attachRole()'

### ISSUE THREAD

**Issue by ellgibug** [Zizaco/entrust#734]
Hello!
I tried to attach role to user, but it doesn't work.
I've made each step in tytorial up to
 `$user->attachRole($admin);`
and then I receive an error. 
`public function attachRole($role)` in EntrustUserTrait and `use EntrustUserTrait;` in User.php exist. Class Role extends EntrustRole.

What could it be? Thanks for help)

**Comment by RayZoey** [comment]
I have the same problem

**Comment by tao0516** [comment]
1、models users lack
2、composer dump-autoload
