### ISSUE TITLE
Laravel 5.4 : Trait method restore has not been applied, because there are collisions with other trait methods on App\User

### ISSUE THREAD

**Issue by diazsasak** [Zizaco/entrust#742]
Its appear that laravel SoftDeletes class and EntrustUserTrait class has method named restore, i try to not using use SofDeletes and its work. so i cant use it together ? :(

![image](https://cloud.githubusercontent.com/assets/7880137/23087860/6f54c770-f5b2-11e6-8e01-a29cd4e37b70.png)
![image](https://cloud.githubusercontent.com/assets/7880137/23087855/63dbb8d6-f5b2-11e6-8bed-598fe5441716.png)

**Comment by exculibar** [comment]
Try this
`class User extends Model implements AuthenticatableInterface
{
    use Authenticatable;
    use EntrustUserTrait { restore as private restoreA; }
    use SoftDeletes { restore as private restoreB; }

    public function restore()
    {
        $this->restoreA();
        $this->restoreB();
    }
}`

**Comment by ogdtarun** [comment]
This solution did worked, Yeahh..  Can you please explain little bit, what is happening here.

**Comment by wzulfikar** [comment]
#749

**Comment by maduonline** [comment]
This works. Thanks @exculibar

**Comment by lbm-trentm** [comment]
@ogdtarun - It's simply aliasing the trait function to avoid a collision. Traits are awesome, but they do have a tendency to be a nuisance as you've found :)

**Comment by roboticsexpert** [comment]
this is not really a bug ....
you should manually implement any function that exist in two or more trait in your class ... this is really basics of OOP ... this can't happen automatically ... @milosdakic

**Comment by oceanwap** [comment]
@Zizaco There are 299 issues pending most of which has been solved already. Can you please close ?

**Comment by profexpress** [comment]
@exculibar Your solution does not work for me. I use Laravel 5.4

> Interface 'App\AuthenticatableInterface' not found

Apart from that, what happened with the `use Notifiable;` line?

Thanks!

**Comment by profexpress** [comment]
Anybody any hint? Thanks!

**Comment by chriys** [comment]
@profexpress hope it's not too late. But the solution of @exculibar didn't work well for me neither. I'm using Larave 5.4.32
Here is an alternative if you can modify one of the conflicting trait:

- Rename the boot with boot + the trait's classname

```
trait DemoTrait
{
    protected static function bootDemoTrait()
    {
         // you don't need to call parent::boot() it will fail otherwise
         // your logic
    }
}
```

This works because Laravel will also look for a boot method name concatenated with the class name.

**Comment by jvzanatta** [comment]
Taking a look at the `restore()` method from the `EntrustUserTrait`:

```    public function restore()
    {   //soft delete undo's
        $result = parent::restore();  // ------> I believe that this is a call to SoftDeletes::restore();
        Cache::tags(Config::get('entrust.role_user_table'))->flush();
        return $result;
    }```

If `$result = parent::restore();` intends to call `SoftDeletes::restore()`, it might be better to only alias the `EntrustUserTrait::restore()` function to something like `entrustRestore()`, then call it whenever you need, and it will do the job for you.

**Comment by childeYin** [comment]
I have this problem  in with lumn with jwt-auth;  It's not worked

**Comment by Tarasovych** [comment]
Same problem here with Laravel 5.5

**Comment by hayjay01** [comment]
> @profexpress hope it's not too late. But the solution of @exculibar didn't work well for me neither. I'm using Larave 5.4.32
> Here is an alternative if you can modify one of the conflicting trait:
> 
> * Rename the boot with boot + the trait's classname
> 
> ```
> trait DemoTrait
> {
>     protected static function bootDemoTrait()
>     {
>          // you don't need to call parent::boot() it will fail otherwise
>          // your logic
>     }
> }
> ```
> This works because Laravel will also look for a boot method name concatenated with the class name.

Best ever solution for this problem. It works!

**Comment by syntaxlexx** [comment]
> class User extends Model implements AuthenticatableInterface
> {
> use Authenticatable;
> use EntrustUserTrait { restore as private restoreA; }
> use SoftDeletes { restore as private restoreB; }
> 
> ```
> public function restore()
> {
>     $this->restoreA();
>     $this->restoreB();
> }
> ```
> }

As for my case:

```php

class User extends Authenticatable
{
     use EntrustUserTrait { restore as private restoreA; }
     use SoftDeletes { restore as private restoreB; }

     /**
     * fix collision on restore methods in SoftDelete trait and Entrust trait
     */
    public function restore()
    {
        $this->restoreA();
        $this->restoreB();
    }

}
```
