### ISSUE TITLE
Views not updating

### ISSUE THREAD

**Issue by jonjie0317** [Zizaco/entrust#768]
Everytime Im installing this package, all of my **view** wont update anymore, even if I try to clear the cache. I have also tried to **empty my views** but the **output** is still the **same**. Why is that? Need Help. Any help will be appreciated.

**Comment by webmake** [comment]
Hello,
did you try change permissions to 777 recursive just for testing on cache dirs, because I suspect that module is installed via composer with userX, but apache isn't authorized to write, and vice versa.
This module works perfect in our projects, we hadn't cache issue at all.
