### ISSUE TITLE
AWS ElasticBeanstalk Deployments Fail due to Entrust

### ISSUE THREAD

**Issue by jcrawford** [Zizaco/entrust#793]
We are using AWS ElasticBeanstalk for our development and production environments.  I had implemented Entrust per your documentation and when I would deploy it would fail on the composer install step.  It would complain about the Laravel 5.3 cache directories not existing.

https://paste.laravel.io/bkApE

I was using version 5.2.x-dev per your documentation and even tried using dev-master and received the same issue.  Something in your library is causing composer to fail when running the install through the elasticbeanstalk deployment process.

I verified this by removing Entrust from the composer.json and also removed the Service Providers, Alias and the User Trait.  Deployments worked perfectly fine after that.

I am not sure what could be causing the issue but figured I would log a ticket with you since a lot of people may be using Laravel and AWS ElasticBeanstalk for deployments.

When using Entrust this is what I received for an error upon deployment
```
 ~/Dropbox/Work/RYNO/htdocs: eb deploy ryno-development
Creating application version archive "app-e9c94-170526_130425".
Uploading: [##################################################] 100% Done...
INFO: Environment update is starting.
INFO: Deploying new version to instance(s).
ERROR: [Instance: i-030aa614c7bdaeb99] Command failed on instance. Return code: 1 Output: (TRUNCATED)...timize


  [InvalidArgumentException]
  Please provide a valid cache path.


Script php artisan optimize handling the post-install-cmd event returned with error code 1.
Hook /opt/elasticbeanstalk/hooks/appdeploy/pre/10_composer_install.sh failed. For more detail, check /var/log/eb-activity.log using console or EB CLI.
INFO: Command execution completed on all instances. Summary: [Successful: 0, Failed: 1].
ERROR: Unsuccessful command execution on instance id(s) 'i-030aa614c7bdaeb99'. Aborting the operation.
ERROR: Failed to deploy application.

ERROR: Failed to deploy application.
```

After removing and before integrating Entrust this is what the deployment process looked like

```
 ~/Dropbox/Work/RYNO/htdocs: eb deploy ryno-development
Creating application version archive "app-c7c2-170526_130929".
Uploading: [##################################################] 100% Done...
INFO: Environment update is starting.
INFO: Deploying new version to instance(s).
INFO: New application version was deployed to running EC2 instances.
INFO: Environment update completed successfully.
```

**Comment by jcrawford** [comment]
6 days without a response, I opted to write my own code for roles and permissions.  Lack of responses made us decide we couldn't use this library!

**Comment by rutvij2292** [comment]
@jcrawford Use Laratrust instead of Entrust.  https://github.com/santigarcor/laratrust

**Comment by PaoloFalomo** [comment]
In your `config/` folder you should have and edit the `entrust.php` file for your needs.

It depends by your `.env` file on which cache driver are using. I suggest to use `
CACHE_DRIVER=array`.

**Comment by jcrawford** [comment]
@PaoloFalomo I had changed the configs and we are using Memcached for caching but thanks.  This package would just not work at all on AWS ElasticBeanstalk when deployed.

**Comment by PaoloFalomo** [comment]
I am using it right now on some apps deployed on AWS ElasticBeanstalk - working perfectly.
