### ISSUE TITLE
issue when creating migrations, laravel 5.3

### ISSUE THREAD

**Issue by Philwn** [Zizaco/entrust#796]
When running:
`php artisan entrust:migration`

It results in the following error:

> Creating migration...
> PHP Fatal error:  Class 'Of\Your\User\Model\User' not found in /var/www/html/pim.dev/vendor/zizaco/entrust/src/commands/MigrationCommand.php on line 85
> 
> 
> 
>   [Symfony\Component\Debug\Exception\FatalErrorException]
>   Class 'Of\Your\User\Model\User' not found

**Comment by Philwn** [comment]
Silly me, fixed

**Comment by deyvsonaguiar** [comment]
Também obtive este erro após rodar um Yes para o seguinte histórico: 

λ php artisan entrust:migration

Tables: roles, role_user, permissions, permission_role
A migration that creates 'roles', 'role_user', 'permissions', 'permission_role' tables will be created in database/migrations directory

 Proceed with the migration creation? [Yes|no] (yes/no) [yes]:
 > yes


Creating migration...

In MigrationCommand.php line 85:

  Class 'Of\Your\User\Model\User' not found

Como resolver?
