### ISSUE TITLE
Lumen 5.4 - Class 'Illuminate\Foundation\Auth\User' not found

### ISSUE THREAD

**Issue by rei-gun** [Zizaco/entrust#806]
I can't seem to get around this error. I've tried "composer update", "composer install", "composer update --no-scripts". 

```
<?php

namespace App\Models;

// use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Authenticatable as AuthenticatableTrait;
use Zizaco\Entrust\Traits\EntrustUserTrait;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{

    use EntrustUserTrait, AuthenticatableTrait; // add this trait to your user model
// bla bla bla
}
```

Is it because Lumen is missing this Laravel core file? Should I install it manually? How?

**Comment by mauvm** [comment]
Try looking in `vendor/` for the `Illuminate\Auth\Authenticatable` trait. Maybe this is the issue: https://github.com/jenssegers/laravel-mongodb/issues/702#issuecomment-184065159

**Comment by rehman94** [comment]
Hey @double-reinbows 
For laravel 5.4 replace <pre><code>use Illuminate\Foundation\Auth\User as Authenticatable;
</code></pre> with
<pre>
<code>use Jenssegers\Mongodb\Auth\User as Authenticatable;
</code></pre>
The final user model would be like this
<pre><code>namespace App;

use Laravel\Passport\HasApiTokens;
use Jenssegers\Mongodb\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;</code></pre>

hope it will work

**Comment by double-reinbows** [comment]
Hi @rehman94,

I've noticed you're using a class from Mongodb however my database mySQL. Do you foresee any issues with this?

**Comment by GontangRagilPrakasa** [comment]
hi @rei-gun can you solved this?

**Comment by rei-gun** [comment]
hi @GontangRagilPrakasa , this was made so long ago I don't even remember what I was trying to do. Sorry
