### ISSUE TITLE
Laravel 5.4 Entrust\Traits can not read config throw Config::get('auth.model')

### ISSUE THREAD

**Issue by vagh** [Zizaco/entrust#817]
In zizaco\entrust\src\Entrust\Traits\EntrustRoleTrait.php line 51:
```
Config::get('auth.model')
```
is undefined，So when I try to delete a role ,Cache a exception like this:
```
Class name must be a valid object or a string
```
because of  `Config::get('auth.model')`  is not defiend in my Auth config

So i try to  change this file
```
return $this->belongsToMany(Config::get('auth.model'), Config::get('entrust.role_user_table'),Config::get('entrust.role_foreign_key'),Config::get('entrust.user_foreign_key'));
```
to
```
return $this->belongsToMany(Config::get('auth.providers.users.model'), Config::get('entrust.role_user_table'),Config::get('entrust.role_foreign_key'),Config::get('entrust.user_foreign_key'));
```

But it is not good in my eye,How can i do?

**Comment by vagh** [comment]
I change my composer.json `"zizaco/entrust": "5.2.x-dev"` to `"zizaco/entrust": "dev-master"` then solved this issues.

**Comment by leandroruel** [comment]
```
Config::get('auth.model')
```
 must be the wrong path to the config file...
i think the right config is
```
 Config::get('providers.users.model')
```
