### ISSUE TITLE
Route middleware for role doesn't work

### ISSUE THREAD

**Issue by rafal-olszewski** [Zizaco/entrust#823]
As the title says, hidding route behind a `role:admin` middleware, does not work:

```
		Route::middleware( [ 'role:admin' ] )->group( function () {
			Route::get( '/test', function () {
				return \App\Statistics::all();
			} );
		} );
```

view returns `HttpExecption` `in Application.php (line 926)`

![image](https://user-images.githubusercontent.com/29777438/29228474-238302f6-7eda-11e7-95ec-060377f077a7.png)

**Comment by fenble** [comment]
if current user doesn't has the admin role, you just need create error view in `resources/views/errors` ,like 403.blade.php ,404.blade.php . it will look more friendly

**Comment by rafal-olszewski** [comment]
That's more friendly, but can I hide resource route behind `role:admin` middleware ?
