### ISSUE TITLE
Error in entrustu:migration

### ISSUE THREAD

**Issue by drjoju** [Zizaco/entrust#826]
Hi, I'm trying to install entrust in Laravel Framework 5.5-dev.

I follow the instructions but when I arrive to 
`php artisan entrust:migration`
an error appears
```
[ReflectionException]
  Method Zizaco\Entrust\MigrationCommand::handle() does not exist
```
I copy/paste the providers and aliases so I'm sure that's correct.

I copy paste the migration and follow the installation so all the rest it's correct.

Anyone has this error?

Thanks and best regards

**Comment by denniskuligin** [comment]
looks like composer wasn't actually installed the entrust package. Try to reinstall it, and run composer dump-autoload

**Comment by githubwyllie** [comment]
I have the same problem. Is there any solution?

**Comment by wmlab03** [comment]
@drjoju @githubwyllie  As per laravel5.5 upgrade release, "Any fire methods present on your Artisan commands should be renamed to handle."

Go to MigrationCommand and rename "fire" method to "handle". You should get it working.

**Comment by justem007** [comment]
Go to the file (vendor-> zizaco-> entrust-> src-> commands-> MigrationCommand.php and change the "fire" method to "handle" and after the command "php artisan entrust: migration" will be generated Migration and just run the "php artisan migrate" command that the tables will be generated in your database.

**Comment by githubwyllie** [comment]
@justem007 @wmlab03 Thanks!

**Comment by Zizaco** [comment]
Closed since #840 was merged

**Comment by icelake0** [comment]
@justem007 its works thanks

**Comment by lovews28** [comment]
but not instead。
