### ISSUE TITLE
Laravel version compatible 5.5

### ISSUE THREAD

**Issue by jitendra-atx** [Zizaco/entrust#848]
Is this package compitible with laravel 5.5 evrsion?

**Comment by aconital** [comment]
I'm having the same issue. It stopped working after I upgraded to 5.5

**Comment by AmruthPillai** [comment]
It's working for me on 5.5.

**Comment by saulomatias** [comment]
@jitendra-atx your file config/auth.php is update with 'providers' => [
    'users' => [
        'driver' => 'eloquent',
        'model' => Namespace\Of\Your\User\Model\User::class,
        'table' => 'users',
    ],
],

**Comment by leandroruel** [comment]
i have the same question, but for sure not. i think some things changed between 5.2 and 5.5 on core.
