### ISSUE TITLE
Too much queries!

### ISSUE THREAD

**Issue by jhemmmm** [Zizaco/entrust#851]
Yes, it is just to fucking much queries. I tried creating a mention system, I tried mentioning 10 users and I got 300+ queries. (It does duplicate queries)

**Comment by tripper54** [comment]
Patch?

**Comment by MaeJhem** [comment]
Patch what?

**Comment by leandroruel** [comment]
you can show us it here? i mean, copy and paste your output here?

**Comment by Zizaco** [comment]
@MaeJhem I will be taking a look at this problem

**Comment by jhemmmm** [comment]
Thanks, You can try creating a mention system and take a look of the output itself.

**Comment by anis-bedhiafi** [comment]
Hi Guys. @MaeJhem  @leandroruel 

I am having the same issue.

For a simple page I have

620 statements were executed, 617 of which were duplicated, 3 unique

It is killing the server

Duplicates are roles and permissions:

select roles.*, role_user.user_id as pivot_user_id, role_user.role_id as pivot_role_id, role_user.created_at as pivot_created_at, role_user.updated_at as pivot_updated_at from roles inner join role_user on roles.id = role_user.role_id where role_user.user_id = '2'

select permissions.*, permission_role.role_id as pivot_role_id, permission_role.permission_id as pivot_permission_id from permissions inner join permission_role on permissions.id = permission_role.permission_id where permission_role.role_id = '2'

I attached a screenshot from debugger.
![entrust-bug](https://user-images.githubusercontent.com/10687639/32794738-02558614-c96a-11e7-867e-3e470c97b5e1.png)

**Comment by jhemmmm** [comment]
@anis-bedhiafi 
Thanks, I hope it got fixed as soon as possible, it is killing the server.

**Comment by dflow** [comment]
any news?

**Comment by leandroruel** [comment]
i think no.

**Comment by tanteng** [comment]
how to solve it

**Comment by daoquangdung** [comment]
I think this might help you
https://github.com/Zizaco/entrust/pull/373/files

**Comment by tatarysh** [comment]
set:
`CACHE_DRIVER=array`
in .env file

and add 'ttl' in confg/cache.php
```
return [
/***/
    'ttl' => 60,
/***/
];
```

**Comment by matteo-gz** [comment]
very good!

**Comment by jhemmmm** [comment]
Dead.
