### ISSUE TITLE
Is it possible to add extra fields or relations to the tables?

### ISSUE THREAD

**Issue by edamian** [Zizaco/entrust#852]
Hi, pardon me for my english.

This is my question if is possible to add extra fields to the tables users, roles and permissions even add a relation with other table, for example if I add in role table a category column and run migration everything should go ok right? or is there a limitation about this?

Thanks for your help!

**Comment by mllnd** [comment]
@edamian 
Had the same idea as well, gonna try to implement this with another table - something like `role_extras`. Then join the corresponding models with Eloquent relationships using primary keys.

**Comment by leandroruel** [comment]
yes you can, just after create the migrations, go to Database/Migrations folder, find the create_table_users or the table name you want modify and add extra fields inside the closure, eg:
```php
$table->integer();
```

https://laravel.com/docs/5.5/migrations#columns
