### ISSUE TITLE
Use with another model, like Organization

### ISSUE THREAD

**Issue by simplenotezy** [Zizaco/entrust#863]
In my application you can create different organisations, and users may be member of many different organisations. In each organisation, the user may have individual roles and permissions.

How could entrust be used to support this behaviour? It currently feels like it's bound to single roles.

**Comment by michalisantoniou6** [comment]
@simplenotezy I needed similar for a project and I created this package. https://github.com/michalisantoniou6/laravel-cerberus

It offers the same functionality, in addition to organization specific roles. I added `forSite` to each method. You can do `$user->hasRoleForSite('admin', $site)`, `$user->hasPermissionForSite('admin', $site)` and so on. I also fixes Laravel 5.5 issues, and has some other improvements. I'm still working on finishing up the documentation, but the switch is simple. This is going live on one of my projects that was using Entrust next week, so I'll be actively maintaining it.

Feel free to check it out.

**Comment by simplenotezy** [comment]
Thanks @michalisantoniou6 - looks really cool your project. Let me know when you have updated the docs - I'd like to leverage the project.
