### ISSUE TITLE
Is this project still live / active?

### ISSUE THREAD

**Issue by G1FEF** [Zizaco/entrust#869]
Hi,

Does anyone know if Zizaco is still maintaining this repo? There are a few bug fixes that need doing to make it fully compatible with Laravel 5.5 that contributers have suggested but there's been no updates to the code for some time now.

**Comment by fatihalp** [comment]
I'm also wonder is active? Want to use in Laravel 5.5

**Comment by ganlvtech** [comment]
Here is a project based on Entrust called NTrust that supports Laravel 5.5, but I haven't try it.
<https://github.com/klaravel/ntrust>

**Comment by berzley** [comment]
What bugs are you having in 5.5? - I'm actively using it with no problems (yet)

**Comment by Zizaco** [comment]
#840 was merged. I strongly believe that it should be fully 5.5 compatible by now. :smiley: 

Anyway I will be doing some cleanup and improvement on the package over the next weeks.
