### ISSUE TITLE
Method Zizaco\Entrust\MigrationCommand::handle() does not exist

### ISSUE THREAD

**Issue by pobeizhang** [Zizaco/entrust#879]
# My environment：

- php7.0
- nginx 1.12.0
- laravel 5.5.23
- "zizaco/entrust": " 5.2.x-dev"

I run 

`php artisan entrust:migration`

Report errors:
`Method Zizaco\Entrust\MigrationCommand::handle() does not exist`

# What should I do to solve this problem？

**Comment by faiverson** [comment]
what about "zizaco/entrust": " dev-master" ?

**Comment by pobeizhang** [comment]
@faiverson According to your method, I really solved the problem I have just met. Thank you very much! But I still think the document should be updated.
