### ISSUE TITLE
Main (default) role

### ISSUE THREAD

**Issue by Subb98** [Zizaco/entrust#886]
```You can have as many Roles as you want for each User and vice versa.```
How to set the main (default) role for the user? For example, a user has four roles: admin, moderator, developer, user. How to make one role the main, more priority? To display it in the View. For example: ```$user->setMainRole('some_role')/getMainRole()```.

**Comment by adelf** [comment]
Don't use entrust in your project. Just make one field in users table. It will be enough.

**Comment by Subb98** [comment]
I solved this case by sets user role in `RegisterController`, in `confirm` method.
