### ISSUE TITLE
can check role permission by model ???

### ISSUE THREAD

**Issue by atikrahman-ew** [Zizaco/entrust#904]
is there any way we can check role permission by model ???????

$user->can(['edit-user', 'create-post']);

Like THat $role->can(['edit-user', 'create-post']); is anything like that possible ???

**Comment by tkovs** [comment]
Do you want to do this?
```php
$role->can(array('this', 'that'));
```

**Comment by atikrahman-ew** [comment]
@tkovs yes wanted to do something like that. but its giving error ....
Call to undefined method Illuminate\Database\Query\Builder::can()

**Comment by atikrahman-ew** [comment]
Solved $role->hasPermission(array('complete-client-form'));
