### ISSUE TITLE
attachPermissions() column roles_id not found

### ISSUE THREAD

**Issue by flexsingit** [Zizaco/entrust#926]
While assigning the permission to a role below error is appearing 

![127 0 0 1 8000 admin roles assign permission 7](https://user-images.githubusercontent.com/25687998/43951738-8160d90c-9cb1-11e8-9d34-6ff98f291ac8.png)

Any help !!!

**Comment by tamimibrahim17** [comment]
re migrate "permission_roles" table, that will help.
