### ISSUE TITLE
supprt for laravel 6 successful

### ISSUE THREAD

**Issue by shinnlu** [Zizaco/entrust#962]
hello, all entrust user, i just do a little modify to support laravel 6 without problem.
but i don't know the procedure to publish the package.
please tell me how to do it.

**Comment by shinnlu** [comment]
there is another guy do the same work:[issue 960](https://github.com/Zizaco/entrust/issues/960)
so, i will keep my version locally.

**Comment by cyborix** [comment]
can you share here please

**Comment by cyborix** [comment]
@shinnlu can help me man..?
